// Command enumvals is a second minigo-generate plugin beside
// tools/stringer: it emits a Values() accessor listing an enum's
// members in declaration order. Two tools over the same package — the
// point of //minigo:generate is that each directive picks its own.
//
// Dual-mode like stringer: func main wraps Main, so the same source
// runs as a real command and interpreted under minigo-generate.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/podhmo/minigo/inspect"
)

func main() {
	os.Exit(Main(os.Args[1:]))
}

// Main is the minigo-generate entry: args are the directive's arguments
// (argv[1:] of the equivalent command), not the process's os.Args.
func Main(args []string) int {
	fs := flag.NewFlagSet("enumvals", flag.ContinueOnError)
	typ := fs.String("type", "", "generate Values() for this named type")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *typ == "" {
		fmt.Fprintln(os.Stderr, "enumvals: -type is required")
		return 2
	}
	gofile := os.Getenv("GOFILEPATH")
	if gofile == "" {
		fmt.Fprintln(os.Stderr, "enumvals: GOFILEPATH is not set (run via minigo-generate)")
		return 2
	}
	dir := filepath.Dir(gofile)
	pkg := inspect.DirOf(dir)
	var target *inspect.Decl
	for _, f := range inspect.Files(pkg) {
		for _, d := range inspect.Decls(f) {
			if d.Name == *typ && inspect.Kind(d) == "type" {
				target = d
			}
		}
	}
	if target == nil {
		fmt.Fprintf(os.Stderr, "enumvals: no type %s in package %s\n", *typ, inspect.Path(pkg))
		return 1
	}
	members := inspect.EnumMembers(target)
	if len(members) == 0 {
		fmt.Fprintf(os.Stderr, "enumvals: type %s has no enum consts\n", *typ)
		return 1
	}
	src := emit(inspect.Name(pkg), *typ, members)
	// go/format is bound natively by the runner — generated code is
	// formatted like a real tool's output.
	if formatted, ferr := format.Source(src); ferr == nil {
		src = formatted
	}
	out := filepath.Join(dir, strings.ToLower(*typ)+"_values.go")
	if err := os.WriteFile(out, src, 0644); err != nil {
		fmt.Fprintln(os.Stderr, "enumvals:", err)
		return 1
	}
	fmt.Println("enumvals: wrote", out)
	return 0
}

// emit renders <type>_values.go: a Values() slice in declaration order
// (EnumMembers preserves source order) — stringer's companion output.
func emit(pkg, typ string, members []*inspect.Decl) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by minigo enumvals -type=%s; DO NOT EDIT.\n\n", typ)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// %sValues lists every %s member in declaration order.\n", typ, typ)
	fmt.Fprintf(&b, "func %sValues() []%s {\n\treturn []%s{\n", typ, typ, typ)
	for _, m := range members {
		fmt.Fprintf(&b, "\t\t%s,\n", m.Name)
	}
	fmt.Fprintf(&b, "\t}\n}\n")
	return []byte(b.String())
}
