// Code generated by convert. DO NOT EDIT.

//go:build e2e
// +build e2e

package e2e

import (
	"context"
	"errors"
	"fmt"

	convutil "github.com/podhmo/minigo/examples/convert-define/convutil"
	"github.com/podhmo/minigo/examples/convert-define/model"
	destination "github.com/podhmo/minigo/examples/convert-define/sampledata/destination"
	funcs "github.com/podhmo/minigo/examples/convert-define/sampledata/funcs"
	source "github.com/podhmo/minigo/examples/convert-define/sampledata/source"
)

// convertSrcUserToDstUser converts source.SrcUser to destination.DstUser.
func convertSrcUserToDstUser(ctx context.Context, ec *model.ErrorCollector, src *source.SrcUser) *destination.DstUser {
	if src == nil {
		return nil
	}
	dst := &destination.DstUser{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Address")
	dst.Address = *convertSrcAddressToDstAddress(ctx, ec, &src.Address)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Details")
	{
		convertedSlice := make([]destination.DstInternalDetail, len(src.Details))
		for i, item := range src.Details {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = *convertSrcInternalDetailToDstInternalDetail(ctx, ec, &item)
			ec.Leave()
		}
		dst.Details = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("CreatedAt")
	dst.CreatedAt = convutil.TimeToString(ctx, ec, src.CreatedAt)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("UpdatedAt")
	dst.UpdatedAt = convutil.PtrTimeToString(ctx, ec, src.UpdatedAt)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("UserID")
	dst.UserID = funcs.UserIDToString(ctx, ec, src.ID)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Contact")
	dst.Contact = funcs.ConvertSrcContactToDstContact(ctx, ec, src.ContactInfo)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("FullName")
	dst.FullName = funcs.MakeFullName(src.FirstName, src.LastName)
	ec.Leave()
	return dst
}

// ConvertSrcUserToDstUser converts source.SrcUser to destination.DstUser.
func ConvertSrcUserToDstUser(ctx context.Context, src *source.SrcUser) (*destination.DstUser, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcUserToDstUser(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcAddressToDstAddress converts source.SrcAddress to destination.DstAddress.
func convertSrcAddressToDstAddress(ctx context.Context, ec *model.ErrorCollector, src *source.SrcAddress) *destination.DstAddress {
	if src == nil {
		return nil
	}
	dst := &destination.DstAddress{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("FullStreet")
	dst.FullStreet = src.Street
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("CityName")
	dst.CityName = src.City
	ec.Leave()
	return dst
}

// ConvertSrcAddressToDstAddress converts source.SrcAddress to destination.DstAddress.
func ConvertSrcAddressToDstAddress(ctx context.Context, src *source.SrcAddress) (*destination.DstAddress, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcAddressToDstAddress(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcInternalDetailToDstInternalDetail converts source.SrcInternalDetail to destination.DstInternalDetail.
func convertSrcInternalDetailToDstInternalDetail(ctx context.Context, ec *model.ErrorCollector, src *source.SrcInternalDetail) *destination.DstInternalDetail {
	if src == nil {
		return nil
	}
	dst := &destination.DstInternalDetail{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ItemCode")
	dst.ItemCode = src.Code
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("LocalizedDesc")
	dst.LocalizedDesc = funcs.Translate(ctx, ec, src.Description)
	ec.Leave()
	return dst
}

// ConvertSrcInternalDetailToDstInternalDetail converts source.SrcInternalDetail to destination.DstInternalDetail.
func ConvertSrcInternalDetailToDstInternalDetail(ctx context.Context, src *source.SrcInternalDetail) (*destination.DstInternalDetail, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcInternalDetailToDstInternalDetail(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcOrderToDstOrder converts source.SrcOrder to destination.DstOrder.
func convertSrcOrderToDstOrder(ctx context.Context, ec *model.ErrorCollector, src *source.SrcOrder) *destination.DstOrder {
	if src == nil {
		return nil
	}
	dst := &destination.DstOrder{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ID")
	dst.ID = src.OrderID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("TotalAmount")
	dst.TotalAmount = src.Amount
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("LineItems")
	{
		convertedSlice := make([]destination.DstItem, len(src.Items))
		for i, item := range src.Items {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = *convertSrcItemToDstItem(ctx, ec, &item)
			ec.Leave()
		}
		dst.LineItems = convertedSlice
	}
	ec.Leave()
	return dst
}

// ConvertSrcOrderToDstOrder converts source.SrcOrder to destination.DstOrder.
func ConvertSrcOrderToDstOrder(ctx context.Context, src *source.SrcOrder) (*destination.DstOrder, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcOrderToDstOrder(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcItemToDstItem converts source.SrcItem to destination.DstItem.
func convertSrcItemToDstItem(ctx context.Context, ec *model.ErrorCollector, src *source.SrcItem) *destination.DstItem {
	if src == nil {
		return nil
	}
	dst := &destination.DstItem{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ProductCode")
	dst.ProductCode = src.SKU
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Count")
	dst.Count = src.Quantity
	ec.Leave()
	return dst
}

// ConvertSrcItemToDstItem converts source.SrcItem to destination.DstItem.
func ConvertSrcItemToDstItem(ctx context.Context, src *source.SrcItem) (*destination.DstItem, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcItemToDstItem(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertComplexSourceToComplexTarget converts source.ComplexSource to destination.ComplexTarget.
func convertComplexSourceToComplexTarget(ctx context.Context, ec *model.ErrorCollector, src *source.ComplexSource) *destination.ComplexTarget {
	if src == nil {
		return nil
	}
	dst := &destination.ComplexTarget{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Ptr")
	if src.Ptr != nil {
		tmp := (*src.Ptr)
		dst.Ptr = &tmp
	} else {
		dst.Ptr = nil
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Slice")
	{
		convertedSlice := make([]destination.SubTarget, len(src.Slice))
		for i, item := range src.Slice {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = *convertSubSourceToSubTarget(ctx, ec, &item)
			ec.Leave()
		}
		dst.Slice = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SliceOfPtrs")
	{
		convertedSlice := make([]*destination.SubTarget, len(src.SliceOfPtrs))
		for i, item := range src.SliceOfPtrs {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = convertSubSourceToSubTarget(ctx, ec, item)
			ec.Leave()
		}
		dst.SliceOfPtrs = convertedSlice
	}
	ec.Leave()
	return dst
}

// ConvertComplexSourceToComplexTarget converts source.ComplexSource to destination.ComplexTarget.
func ConvertComplexSourceToComplexTarget(ctx context.Context, src *source.ComplexSource) (*destination.ComplexTarget, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertComplexSourceToComplexTarget(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSubSourceToSubTarget converts source.SubSource to destination.SubTarget.
func convertSubSourceToSubTarget(ctx context.Context, ec *model.ErrorCollector, src *source.SubSource) *destination.SubTarget {
	if src == nil {
		return nil
	}
	dst := &destination.SubTarget{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	return dst
}

// ConvertSubSourceToSubTarget converts source.SubSource to destination.SubTarget.
func ConvertSubSourceToSubTarget(ctx context.Context, src *source.SubSource) (*destination.SubTarget, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSubSourceToSubTarget(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSourceWithMapToTargetWithMap converts source.SourceWithMap to destination.TargetWithMap.
func convertSourceWithMapToTargetWithMap(ctx context.Context, ec *model.ErrorCollector, src *source.SourceWithMap) *destination.TargetWithMap {
	if src == nil {
		return nil
	}
	dst := &destination.TargetWithMap{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ValueMap")
	{
		convertedMap := make(map[string]destination.SubTarget, len(src.ValueMap))
		for key, value := range src.ValueMap {
			ec.Enter(fmt.Sprintf("[%v]", key))
			convertedMap[key] = *convertSubSourceToSubTarget(ctx, ec, &value)
			ec.Leave()
		}
		dst.ValueMap = convertedMap
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrMap")
	{
		convertedMap := make(map[string]*destination.SubTarget, len(src.PtrMap))
		for key, value := range src.PtrMap {
			ec.Enter(fmt.Sprintf("[%v]", key))
			convertedMap[key] = convertSubSourceToSubTarget(ctx, ec, value)
			ec.Leave()
		}
		dst.PtrMap = convertedMap
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("StringToStr")
	{
		convertedMap := make(map[string]string, len(src.StringToStr))
		for key, value := range src.StringToStr {
			ec.Enter(fmt.Sprintf("[%v]", key))
			convertedMap[key] = value
			ec.Leave()
		}
		dst.StringToStr = convertedMap
	}
	ec.Leave()
	return dst
}

// ConvertSourceWithMapToTargetWithMap converts source.SourceWithMap to destination.TargetWithMap.
func ConvertSourceWithMapToTargetWithMap(ctx context.Context, src *source.SourceWithMap) (*destination.TargetWithMap, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSourceWithMapToTargetWithMap(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcNestedToDstNested converts source.SrcNested to destination.DstNested.
func convertSrcNestedToDstNested(ctx context.Context, ec *model.ErrorCollector, src *source.SrcNested) *destination.DstNested {
	if src == nil {
		return nil
	}
	dst := &destination.DstNested{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Inner")
	dst.Inner = *convertSrcNestedInnerToDstNestedInner(ctx, ec, &src.Inner)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PIn")
	dst.PIn = convertSrcNestedInnerToDstNestedInner(ctx, ec, src.PIn)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Inner.ID")
	dst.Inner.ID = src.ID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Flat")
	dst.Flat = src.Inner.Value
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Tag")
	if src.PIn != nil {
		dst.Tag = src.PIn.Value
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PIn.Value")
	if dst.PIn == nil {
		dst.PIn = &destination.DstNestedInner{}
	}
	dst.PIn.Value = src.Name
	ec.Leave()
	return dst
}

// ConvertSrcNestedToDstNested converts source.SrcNested to destination.DstNested.
func ConvertSrcNestedToDstNested(ctx context.Context, src *source.SrcNested) (*destination.DstNested, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcNestedToDstNested(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcShapesToDstShapes converts source.SrcShapes to destination.DstShapes.
func convertSrcShapesToDstShapes(ctx context.Context, ec *model.ErrorCollector, src *source.SrcShapes) *destination.DstShapes {
	if src == nil {
		return nil
	}
	dst := &destination.DstShapes{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrToVal")
	if src.PtrToVal != nil {
		dst.PtrToVal = int64((*src.PtrToVal))
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ValToPtr")
	{
		tmp := int64(src.ValToPtr)
		dst.ValToPtr = &tmp
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrPtr")
	if src.PtrPtr != nil {
		tmp := convertSrcLeafToDstLeaf(ctx, ec, (*src.PtrPtr))
		dst.PtrPtr = &tmp
	} else {
		dst.PtrPtr = nil
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SlicePP")
	{
		convertedSlice := make([]**destination.DstLeaf, len(src.SlicePP))
		for i, item := range src.SlicePP {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = func() **destination.DstLeaf {
				if item == nil {
					return nil
				}
				tmp := convertSrcLeafToDstLeaf(ctx, ec, (*item))
				return &tmp
			}()
			ec.Leave()
		}
		dst.SlicePP = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("MapPP")
	{
		convertedMap := make(map[string]**destination.DstLeaf, len(src.MapPP))
		for key, value := range src.MapPP {
			ec.Enter(fmt.Sprintf("[%v]", key))
			convertedMap[key] = func() **destination.DstLeaf {
				if value == nil {
					return nil
				}
				tmp := convertSrcLeafToDstLeaf(ctx, ec, (*value))
				return &tmp
			}()
			ec.Leave()
		}
		dst.MapPP = convertedMap
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SlicePtrVal")
	{
		convertedSlice := make([]int64, len(src.SlicePtrVal))
		for i, item := range src.SlicePtrVal {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = func() int64 {
				if item == nil {
					var z int64
					return z
				}
				return int64((*item))
			}()
			ec.Leave()
		}
		dst.SlicePtrVal = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SliceValPtr")
	{
		convertedSlice := make([]*int64, len(src.SliceValPtr))
		for i, item := range src.SliceValPtr {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = func() *int64 {
				tmp := int64(item)
				return &tmp
			}()
			ec.Leave()
		}
		dst.SliceValPtr = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Nested")
	{
		convertedSlice := make([][]int64, len(src.Nested))
		for i, item := range src.Nested {
			ec.Enter(fmt.Sprintf("[%d]", i))
			convertedSlice[i] = func() []int64 {
				convertedSlice := make([]int64, len(item))
				for i, item := range item {
					ec.Enter(fmt.Sprintf("[%d]", i))
					convertedSlice[i] = int64(item)
					ec.Leave()
				}
				return convertedSlice
			}()
			ec.Leave()
		}
		dst.Nested = convertedSlice
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("MapSlice")
	{
		convertedMap := make(map[int64][]int64, len(src.MapSlice))
		for key, value := range src.MapSlice {
			ec.Enter(fmt.Sprintf("[%v]", key))
			convertedMap[int64(key)] = func() []int64 {
				convertedSlice := make([]int64, len(value))
				for i, item := range value {
					ec.Enter(fmt.Sprintf("[%d]", i))
					convertedSlice[i] = func() int64 {
						if item == nil {
							var z int64
							return z
						}
						return int64((*item))
					}()
					ec.Leave()
				}
				return convertedSlice
			}()
			ec.Leave()
		}
		dst.MapSlice = convertedMap
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Arr")
	{
		for i, item := range src.Arr {
			ec.Enter(fmt.Sprintf("[%d]", i))
			dst.Arr[i] = func() int64 {
				if item == nil {
					var z int64
					return z
				}
				return int64((*item))
			}()
			ec.Leave()
		}
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PSlice")
	if src.PSlice != nil {
		dst.PSlice = func() []int64 {
			convertedSlice := make([]int64, len((*src.PSlice)))
			for i, item := range *src.PSlice {
				ec.Enter(fmt.Sprintf("[%d]", i))
				convertedSlice[i] = int64(item)
				ec.Leave()
			}
			return convertedSlice
		}()
	}
	ec.Leave()
	return dst
}

// ConvertSrcShapesToDstShapes converts source.SrcShapes to destination.DstShapes.
func ConvertSrcShapesToDstShapes(ctx context.Context, src *source.SrcShapes) (*destination.DstShapes, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcShapesToDstShapes(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcContactToDstContact converts source.SrcContact to destination.DstContact.
//
// Fields that are not populated by this converter:
//   - EmailAddress
//   - PhoneNumber
func convertSrcContactToDstContact(ctx context.Context, ec *model.ErrorCollector, src *source.SrcContact) *destination.DstContact {
	if src == nil {
		return nil
	}
	dst := &destination.DstContact{}
	return dst
}

// ConvertSrcContactToDstContact converts source.SrcContact to destination.DstContact.
//
// Fields that are not populated by this converter:
//   - EmailAddress
//   - PhoneNumber
func ConvertSrcContactToDstContact(ctx context.Context, src *source.SrcContact) (*destination.DstContact, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcContactToDstContact(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcNestedInnerToDstNestedInner converts source.SrcNestedInner to destination.DstNestedInner.
func convertSrcNestedInnerToDstNestedInner(ctx context.Context, ec *model.ErrorCollector, src *source.SrcNestedInner) *destination.DstNestedInner {
	if src == nil {
		return nil
	}
	dst := &destination.DstNestedInner{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ID")
	dst.ID = src.ID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	return dst
}

// ConvertSrcNestedInnerToDstNestedInner converts source.SrcNestedInner to destination.DstNestedInner.
func ConvertSrcNestedInnerToDstNestedInner(ctx context.Context, src *source.SrcNestedInner) (*destination.DstNestedInner, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcNestedInnerToDstNestedInner(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcLeafToDstLeaf converts source.SrcLeaf to destination.DstLeaf.
func convertSrcLeafToDstLeaf(ctx context.Context, ec *model.ErrorCollector, src *source.SrcLeaf) *destination.DstLeaf {
	if src == nil {
		return nil
	}
	dst := &destination.DstLeaf{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("V")
	dst.V = int64(src.V)
	ec.Leave()
	return dst
}

// ConvertSrcLeafToDstLeaf converts source.SrcLeaf to destination.DstLeaf.
func ConvertSrcLeafToDstLeaf(ctx context.Context, src *source.SrcLeaf) (*destination.DstLeaf, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcLeafToDstLeaf(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}
