// Code generated by convert. DO NOT EDIT.

//go:build e2e

package e2e

import (
	context "context"
	errors "errors"
	fmt "fmt"

	convutil "github.com/podhmo/minigo/examples/convert-define/convutil"
	model "github.com/podhmo/minigo/examples/convert-define/model"
	destination "github.com/podhmo/minigo/examples/convert-define/sampledata/destination"
	funcs "github.com/podhmo/minigo/examples/convert-define/sampledata/funcs"
	source "github.com/podhmo/minigo/examples/convert-define/sampledata/source"
)

// convertSrcUserToDstUser converts source.SrcUser to destination.DstUser.
func convertSrcUserToDstUser(ctx context.Context, ec *model.ErrorCollector, src *source.SrcUser) *destination.DstUser {
	if src == nil {
		return nil
	}
	dst := &destination.DstUser{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Address")
	dst.Address = *convertSrcAddressToDstAddress(ctx, ec, &src.Address)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Details")
	{
		s := make([]destination.DstInternalDetail, len(src.Details))
		for i, item := range src.Details {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = *convertSrcInternalDetailToDstInternalDetail(ctx, ec, &item)
			ec.Leave()
		}
		dst.Details = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("CreatedAt")
	dst.CreatedAt = convutil.TimeToString(ctx, ec, src.CreatedAt)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("UpdatedAt")
	dst.UpdatedAt = convutil.PtrTimeToString(ctx, ec, src.UpdatedAt)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("UserID")
	dst.UserID = funcs.UserIDToString(ctx, ec, src.ID)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Contact")
	dst.Contact = funcs.ConvertSrcContactToDstContact(ctx, ec, src.ContactInfo)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("FullName")
	dst.FullName = funcs.MakeFullName(src.FirstName, src.LastName)
	ec.Leave()
	return dst
}

// ConvertSrcUserToDstUser converts source.SrcUser to destination.DstUser.
func ConvertSrcUserToDstUser(ctx context.Context, src *source.SrcUser) (*destination.DstUser, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcUserToDstUser(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcAddressToDstAddress converts source.SrcAddress to destination.DstAddress.
func convertSrcAddressToDstAddress(ctx context.Context, ec *model.ErrorCollector, src *source.SrcAddress) *destination.DstAddress {
	if src == nil {
		return nil
	}
	dst := &destination.DstAddress{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("FullStreet")
	dst.FullStreet = src.Street
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("CityName")
	dst.CityName = src.City
	ec.Leave()
	return dst
}

// ConvertSrcAddressToDstAddress converts source.SrcAddress to destination.DstAddress.
func ConvertSrcAddressToDstAddress(ctx context.Context, src *source.SrcAddress) (*destination.DstAddress, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcAddressToDstAddress(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcInternalDetailToDstInternalDetail converts source.SrcInternalDetail to destination.DstInternalDetail.
func convertSrcInternalDetailToDstInternalDetail(ctx context.Context, ec *model.ErrorCollector, src *source.SrcInternalDetail) *destination.DstInternalDetail {
	if src == nil {
		return nil
	}
	dst := &destination.DstInternalDetail{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ItemCode")
	dst.ItemCode = src.Code
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("LocalizedDesc")
	dst.LocalizedDesc = funcs.Translate(ctx, ec, src.Description)
	ec.Leave()
	return dst
}

// ConvertSrcInternalDetailToDstInternalDetail converts source.SrcInternalDetail to destination.DstInternalDetail.
func ConvertSrcInternalDetailToDstInternalDetail(ctx context.Context, src *source.SrcInternalDetail) (*destination.DstInternalDetail, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcInternalDetailToDstInternalDetail(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcOrderToDstOrder converts source.SrcOrder to destination.DstOrder.
func convertSrcOrderToDstOrder(ctx context.Context, ec *model.ErrorCollector, src *source.SrcOrder) *destination.DstOrder {
	if src == nil {
		return nil
	}
	dst := &destination.DstOrder{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ID")
	dst.ID = src.OrderID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("TotalAmount")
	dst.TotalAmount = src.Amount
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("LineItems")
	{
		s := make([]destination.DstItem, len(src.Items))
		for i, item := range src.Items {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = *convertSrcItemToDstItem(ctx, ec, &item)
			ec.Leave()
		}
		dst.LineItems = s
	}
	ec.Leave()
	return dst
}

// ConvertSrcOrderToDstOrder converts source.SrcOrder to destination.DstOrder.
func ConvertSrcOrderToDstOrder(ctx context.Context, src *source.SrcOrder) (*destination.DstOrder, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcOrderToDstOrder(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcItemToDstItem converts source.SrcItem to destination.DstItem.
func convertSrcItemToDstItem(ctx context.Context, ec *model.ErrorCollector, src *source.SrcItem) *destination.DstItem {
	if src == nil {
		return nil
	}
	dst := &destination.DstItem{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ProductCode")
	dst.ProductCode = src.SKU
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Count")
	dst.Count = src.Quantity
	ec.Leave()
	return dst
}

// ConvertSrcItemToDstItem converts source.SrcItem to destination.DstItem.
func ConvertSrcItemToDstItem(ctx context.Context, src *source.SrcItem) (*destination.DstItem, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcItemToDstItem(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertComplexSourceToComplexTarget converts source.ComplexSource to destination.ComplexTarget.
func convertComplexSourceToComplexTarget(ctx context.Context, ec *model.ErrorCollector, src *source.ComplexSource) *destination.ComplexTarget {
	if src == nil {
		return nil
	}
	dst := &destination.ComplexTarget{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Ptr")
	{
		var p *string
		if src.Ptr != nil {
			v := (*src.Ptr)
			p = &v
		}
		dst.Ptr = p
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Slice")
	{
		s := make([]destination.SubTarget, len(src.Slice))
		for i, item := range src.Slice {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = *convertSubSourceToSubTarget(ctx, ec, &item)
			ec.Leave()
		}
		dst.Slice = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SliceOfPtrs")
	{
		s := make([]*destination.SubTarget, len(src.SliceOfPtrs))
		for i, item := range src.SliceOfPtrs {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = convertSubSourceToSubTarget(ctx, ec, item)
			ec.Leave()
		}
		dst.SliceOfPtrs = s
	}
	ec.Leave()
	return dst
}

// ConvertComplexSourceToComplexTarget converts source.ComplexSource to destination.ComplexTarget.
func ConvertComplexSourceToComplexTarget(ctx context.Context, src *source.ComplexSource) (*destination.ComplexTarget, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertComplexSourceToComplexTarget(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSubSourceToSubTarget converts source.SubSource to destination.SubTarget.
func convertSubSourceToSubTarget(ctx context.Context, ec *model.ErrorCollector, src *source.SubSource) *destination.SubTarget {
	if src == nil {
		return nil
	}
	dst := &destination.SubTarget{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	return dst
}

// ConvertSubSourceToSubTarget converts source.SubSource to destination.SubTarget.
func ConvertSubSourceToSubTarget(ctx context.Context, src *source.SubSource) (*destination.SubTarget, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSubSourceToSubTarget(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSourceWithMapToTargetWithMap converts source.SourceWithMap to destination.TargetWithMap.
func convertSourceWithMapToTargetWithMap(ctx context.Context, ec *model.ErrorCollector, src *source.SourceWithMap) *destination.TargetWithMap {
	if src == nil {
		return nil
	}
	dst := &destination.TargetWithMap{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ValueMap")
	{
		m := make(map[string]destination.SubTarget, len(src.ValueMap))
		for key, value := range src.ValueMap {
			ec.Enter(fmt.Sprintf("[%v]", key))
			m[key] = *convertSubSourceToSubTarget(ctx, ec, &value)
			ec.Leave()
		}
		dst.ValueMap = m
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrMap")
	{
		m := make(map[string]*destination.SubTarget, len(src.PtrMap))
		for key, value := range src.PtrMap {
			ec.Enter(fmt.Sprintf("[%v]", key))
			m[key] = convertSubSourceToSubTarget(ctx, ec, value)
			ec.Leave()
		}
		dst.PtrMap = m
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("StringToStr")
	{
		m := make(map[string]string, len(src.StringToStr))
		for key, value := range src.StringToStr {
			ec.Enter(fmt.Sprintf("[%v]", key))
			m[key] = value
			ec.Leave()
		}
		dst.StringToStr = m
	}
	ec.Leave()
	return dst
}

// ConvertSourceWithMapToTargetWithMap converts source.SourceWithMap to destination.TargetWithMap.
func ConvertSourceWithMapToTargetWithMap(ctx context.Context, src *source.SourceWithMap) (*destination.TargetWithMap, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSourceWithMapToTargetWithMap(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcNestedToDstNested converts source.SrcNested to destination.DstNested.
func convertSrcNestedToDstNested(ctx context.Context, ec *model.ErrorCollector, src *source.SrcNested) *destination.DstNested {
	if src == nil {
		return nil
	}
	dst := &destination.DstNested{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Inner")
	dst.Inner = *convertSrcNestedInnerToDstNestedInner(ctx, ec, &src.Inner)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PIn")
	dst.PIn = convertSrcNestedInnerToDstNestedInner(ctx, ec, src.PIn)
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Inner.ID")
	dst.Inner.ID = src.ID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Flat")
	dst.Flat = src.Inner.Value
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Tag")
	if src.PIn != nil {
		dst.Tag = src.PIn.Value
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PIn.Value")
	if dst.PIn == nil {
		dst.PIn = &destination.DstNestedInner{}
	}
	dst.PIn.Value = src.Name
	ec.Leave()
	return dst
}

// ConvertSrcNestedToDstNested converts source.SrcNested to destination.DstNested.
func ConvertSrcNestedToDstNested(ctx context.Context, src *source.SrcNested) (*destination.DstNested, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcNestedToDstNested(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcShapesToDstShapes converts source.SrcShapes to destination.DstShapes.
func convertSrcShapesToDstShapes(ctx context.Context, ec *model.ErrorCollector, src *source.SrcShapes) *destination.DstShapes {
	if src == nil {
		return nil
	}
	dst := &destination.DstShapes{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrToVal")
	{
		var v int64
		if src.PtrToVal != nil {
			v = int64((*src.PtrToVal))
		}
		dst.PtrToVal = v
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ValToPtr")
	{
		v := int64(src.ValToPtr)
		dst.ValToPtr = &v
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PtrPtr")
	{
		var p **destination.DstLeaf
		if src.PtrPtr != nil {
			v := convertSrcLeafToDstLeaf(ctx, ec, (*src.PtrPtr))
			p = &v
		}
		dst.PtrPtr = p
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SlicePP")
	{
		s := make([]**destination.DstLeaf, len(src.SlicePP))
		for i, item := range src.SlicePP {
			ec.Enter(fmt.Sprintf("[%d]", i))
			var p **destination.DstLeaf
			if item != nil {
				v := convertSrcLeafToDstLeaf(ctx, ec, (*item))
				p = &v
			}
			s[i] = p
			ec.Leave()
		}
		dst.SlicePP = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("MapPP")
	{
		m := make(map[string]**destination.DstLeaf, len(src.MapPP))
		for key, value := range src.MapPP {
			ec.Enter(fmt.Sprintf("[%v]", key))
			var p **destination.DstLeaf
			if value != nil {
				v := convertSrcLeafToDstLeaf(ctx, ec, (*value))
				p = &v
			}
			m[key] = p
			ec.Leave()
		}
		dst.MapPP = m
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SlicePtrVal")
	{
		s := make([]int64, len(src.SlicePtrVal))
		for i, item := range src.SlicePtrVal {
			ec.Enter(fmt.Sprintf("[%d]", i))
			var v int64
			if item != nil {
				v = int64((*item))
			}
			s[i] = v
			ec.Leave()
		}
		dst.SlicePtrVal = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("SliceValPtr")
	{
		s := make([]*int64, len(src.SliceValPtr))
		for i, item := range src.SliceValPtr {
			ec.Enter(fmt.Sprintf("[%d]", i))
			v := int64(item)
			s[i] = &v
			ec.Leave()
		}
		dst.SliceValPtr = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Nested")
	{
		s := make([][]int64, len(src.Nested))
		for i, item := range src.Nested {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s2 := make([]int64, len(item))
			for i2, item2 := range item {
				ec.Enter(fmt.Sprintf("[%d]", i2))
				s2[i2] = int64(item2)
				ec.Leave()
			}
			s[i] = s2
			ec.Leave()
		}
		dst.Nested = s
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("MapSlice")
	{
		m := make(map[int64][]int64, len(src.MapSlice))
		for key, value := range src.MapSlice {
			ec.Enter(fmt.Sprintf("[%v]", key))
			s := make([]int64, len(value))
			for i, item := range value {
				ec.Enter(fmt.Sprintf("[%d]", i))
				var v int64
				if item != nil {
					v = int64((*item))
				}
				s[i] = v
				ec.Leave()
			}
			m[int64(key)] = s
			ec.Leave()
		}
		dst.MapSlice = m
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Arr")
	{
		var a [2]int64
		for i, item := range src.Arr {
			ec.Enter(fmt.Sprintf("[%d]", i))
			var v int64
			if item != nil {
				v = int64((*item))
			}
			a[i] = v
			ec.Leave()
		}
		dst.Arr = a
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("PSlice")
	{
		var v []int64
		if src.PSlice != nil {
			s := make([]int64, len((*src.PSlice)))
			for i, item := range *src.PSlice {
				ec.Enter(fmt.Sprintf("[%d]", i))
				s[i] = int64(item)
				ec.Leave()
			}
			v = s
		}
		dst.PSlice = v
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedIDs")
	{
		s := make([]int64, len(src.NamedIDs))
		for i, item := range src.NamedIDs {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = int64(item)
			ec.Leave()
		}
		dst.NamedIDs = destination.DstIDs(s)
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedItems")
	{
		s := make([]destination.DstLeaf, len(src.NamedItems))
		for i, item := range src.NamedItems {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = *convertSrcLeafToDstLeaf(ctx, ec, &item)
			ec.Leave()
		}
		dst.NamedItems = destination.DstLeafList(s)
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedPtr")
	dst.NamedPtr = destination.DstPtr(convertSrcLeafToDstLeaf(ctx, ec, src.NamedPtr))
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedPtrVal")
	{
		var v destination.DstLeaf
		if src.NamedPtrVal != nil {
			v = *convertSrcLeafToDstLeaf(ctx, ec, &(*src.NamedPtrVal))
		}
		dst.NamedPtrVal = destination.DstLeaf(v)
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedValPtr")
	{
		v := *convertSrcLeafToDstLeaf(ctx, ec, &src.NamedValPtr)
		dst.NamedValPtr = destination.DstPtr(&v)
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("NamedMap")
	{
		m := make(map[string]int64, len(src.NamedMap))
		for key, value := range src.NamedMap {
			ec.Enter(fmt.Sprintf("[%v]", key))
			m[key] = int64(value)
			ec.Leave()
		}
		dst.NamedMap = destination.DstScores(m)
	}
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("RawIDs")
	{
		s := make([]int64, len(src.RawIDs))
		for i, item := range src.RawIDs {
			ec.Enter(fmt.Sprintf("[%d]", i))
			s[i] = int64(item)
			ec.Leave()
		}
		dst.RawIDs = destination.DstIDs(s)
	}
	ec.Leave()
	return dst
}

// ConvertSrcShapesToDstShapes converts source.SrcShapes to destination.DstShapes.
func ConvertSrcShapesToDstShapes(ctx context.Context, src *source.SrcShapes) (*destination.DstShapes, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcShapesToDstShapes(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcContactToDstContact converts source.SrcContact to destination.DstContact.
//
// Fields that are not populated by this converter:
//   - EmailAddress
//   - PhoneNumber
func convertSrcContactToDstContact(ctx context.Context, ec *model.ErrorCollector, src *source.SrcContact) *destination.DstContact {
	if src == nil {
		return nil
	}
	dst := &destination.DstContact{}
	return dst
}

// ConvertSrcContactToDstContact converts source.SrcContact to destination.DstContact.
//
// Fields that are not populated by this converter:
//   - EmailAddress
//   - PhoneNumber
func ConvertSrcContactToDstContact(ctx context.Context, src *source.SrcContact) (*destination.DstContact, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcContactToDstContact(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcNestedInnerToDstNestedInner converts source.SrcNestedInner to destination.DstNestedInner.
func convertSrcNestedInnerToDstNestedInner(ctx context.Context, ec *model.ErrorCollector, src *source.SrcNestedInner) *destination.DstNestedInner {
	if src == nil {
		return nil
	}
	dst := &destination.DstNestedInner{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("ID")
	dst.ID = src.ID
	ec.Leave()
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("Value")
	dst.Value = src.Value
	ec.Leave()
	return dst
}

// ConvertSrcNestedInnerToDstNestedInner converts source.SrcNestedInner to destination.DstNestedInner.
func ConvertSrcNestedInnerToDstNestedInner(ctx context.Context, src *source.SrcNestedInner) (*destination.DstNestedInner, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcNestedInnerToDstNestedInner(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}

// convertSrcLeafToDstLeaf converts source.SrcLeaf to destination.DstLeaf.
func convertSrcLeafToDstLeaf(ctx context.Context, ec *model.ErrorCollector, src *source.SrcLeaf) *destination.DstLeaf {
	if src == nil {
		return nil
	}
	dst := &destination.DstLeaf{}
	if ec.MaxErrorsReached() {
		return dst
	}
	ec.Enter("V")
	dst.V = int64(src.V)
	ec.Leave()
	return dst
}

// ConvertSrcLeafToDstLeaf converts source.SrcLeaf to destination.DstLeaf.
func ConvertSrcLeafToDstLeaf(ctx context.Context, src *source.SrcLeaf) (*destination.DstLeaf, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector(0)
	dst := convertSrcLeafToDstLeaf(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}
