package main

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/podhmo/minigo"
	"github.com/podhmo/minigo/index"
)

// `minigo gen-intrinsics` emits a Bind table for a package's exported
// members: functions become WrapFunc reflect adapters, vars/consts become
// ValueOf snapshots, types become synthetic named-basic typedefs so
// `var x pkg.T` declares host-typed variables (their values stay boxed
// GoValues and pass through the host-boundary coerce). The generated
// file is ordinary Go — the embedding app calls install.Bind(engine).

var tmplGenIntrinsics = template.Must(template.New("install.go").Parse(`// Code generated by minigo gen-intrinsics. DO NOT EDIT.

package {{ .PackageName }}

import (
	"{{ .PackagePath }}"
	"github.com/podhmo/minigo"
	"github.com/podhmo/minigo/runtime"
)

// Bind registers the exported members of "{{ .PackagePath }}" on the engine.
func Bind(e *minigo.Engine) {
	e.Bind("{{ .PackagePath }}", map[string]runtime.Value{
{{- range .FuncSymbols }}
		"{{ . }}": minigo.WrapFunc("{{ $.PackagePath }}.{{ . }}", {{ $.PackageName }}.{{ . }}),
{{- end }}
{{- range .ValueSymbols }}
		"{{ . }}": minigo.ValueOf({{ $.PackageName }}.{{ . }}),
{{- end }}
{{- range .TypeSymbols }}
		"{{ . }}": &runtime.TypeDef{Name: "{{ . }}", Kind: runtime.KindNamedBasic, Pkg: &runtime.Package{Path: "{{ $.PackagePath }}", Name: "{{ $.PackageName }}"}},
{{- end }}
	})
}
`))

func genIntrinsics(ctx context.Context, args []string) error {
	var output string
	var refs []string
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "-output" || a == "--output":
			i++
			if i >= len(args) {
				return fmt.Errorf("-output requires a directory")
			}
			output = args[i]
		case a == "-h" || a == "--help":
			return fmt.Errorf("usage: minigo gen-intrinsics -output <dir> <pkg>...")
		default:
			refs = append(refs, a)
		}
	}
	if output == "" {
		return fmt.Errorf("gen-intrinsics: -output <dir> is required")
	}
	if len(refs) == 0 {
		return fmt.Errorf("gen-intrinsics: at least one package is required")
	}
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	e := minigo.NewEngine(cwd)
	for _, ref := range refs {
		if err := genOne(ctx, e, output, ref); err != nil {
			return err
		}
	}
	return nil
}

func genOne(ctx context.Context, e *minigo.Engine, output, ref string) error {
	p, err := e.Package(ctx, ref)
	if err != nil {
		return fmt.Errorf("gen-intrinsics %s: %w", ref, err)
	}
	if p.Index == nil {
		return fmt.Errorf("gen-intrinsics %s: package has no source index (bound package?)", ref)
	}
	var funcs, values, types []string
	for _, d := range p.Index.Funcs {
		if d.Kind != index.FuncDecl || !ast.IsExported(d.Name) {
			continue
		}
		if tp := d.Func.Type.TypeParams; tp != nil && len(tp.List) > 0 {
			continue // generic functions have no single callable form
		}
		funcs = append(funcs, d.Name)
	}
	for _, d := range p.Index.Vars {
		if ast.IsExported(d.Name) {
			values = append(values, d.Name)
		}
	}
	for _, d := range p.Index.Consts {
		if ast.IsExported(d.Name) {
			values = append(values, d.Name)
		}
	}
	for name, ti := range p.Index.Types {
		if !ast.IsExported(name) {
			continue
		}
		if ts, ok := ti.Decl.Spec.(*ast.TypeSpec); ok && ts.TypeParams != nil && len(ts.TypeParams.List) > 0 {
			continue // generic types have no single reflect-free form
		}
		types = append(types, name)
	}
	sort.Strings(funcs)
	sort.Strings(values)
	sort.Strings(types)

	params := struct {
		PackageName  string
		PackagePath  string
		FuncSymbols  []string
		ValueSymbols []string
		TypeSymbols  []string
	}{p.Name, p.Path, funcs, values, types}

	dir := filepath.Join(output, filepath.FromSlash(p.Path))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmplGenIntrinsics.Execute(&buf, params); err != nil {
		return err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gen-intrinsics %s: formatting generated source: %w", ref, err)
	}
	name := filepath.Join(dir, "install.go")
	if err := os.WriteFile(name, src, 0o644); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "generated", name)
	return nil
}
