package generator

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/printer"
	"go/token"
	"log/slog"
	"maps"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"github.com/podhmo/minigo/examples/convert-define/model"
	xinspect "github.com/podhmo/minigo/inspect"
	"github.com/podhmo/minigo/runtime"
)

const codeTemplate = `
// Code generated by convert. DO NOT EDIT.
{{ .Header -}}
package {{ .PackageName }}

import (
	{{- range $path, $alias := .Imports }}
	{{ $alias }} "{{ $path }}"
	{{- end }}
)

{{ range .Pairs -}}
// {{ .ConvName }} converts {{ .SrcTypeName }} to {{ .DstTypeName }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
{{- if .Warnings }}
//
// Generation warnings — the reported assignments may not compile:
{{- range .Warnings }}
//   - {{ . }}
{{- end }}
{{- end }}
func {{ .ConvName }}(ctx context.Context, ec *model.ErrorCollector, src *{{ .SrcTypeName }}) *{{ .DstTypeName }} {
	if src == nil {
		return nil
	}
	dst := &{{ .DstTypeName }}{}
	{{ range .Fields -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	{{ .Assign }}
	ec.Leave()
	{{ end -}}
	{{ range .Pair.Computed -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	{{ .Prelude }}dst.{{ .DstName }} = {{ .Expr }}
	ec.Leave()
	{{ end -}}
	return dst
}

// {{ .PublicName }} converts {{ .SrcTypeName }} to {{ .DstTypeName }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
{{- if .Warnings }}
//
// Generation warnings — the reported assignments may not compile:
{{- range .Warnings }}
//   - {{ . }}
{{- end }}
{{- end }}
func {{ .PublicName }}(ctx context.Context, src *{{ .SrcTypeName }}) (*{{ .DstTypeName }}, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector({{ .Pair.MaxErrors }})
	dst := {{ .ConvName }}(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}
{{ end }}
`

type TemplateData struct {
	PackageName string
	Imports     map[string]string
	Pairs       []TemplatePair
	Header      string
}

type TemplatePair struct {
	SrcType        *model.StructInfo
	DstType        *model.StructInfo
	Fields         []FieldMap
	Pair           model.ConversionPair
	UnmappedFields []string
	// Warnings are generate-time diagnostics (e.g. a leaf field pair
	// that falls back to a raw assignment the compiler will reject);
	// they render into the converter's doc comment.
	Warnings []string
	// SrcTypeName/DstTypeName are the qualified struct names as
	// spelled in the generated file.
	SrcTypeName string
	DstTypeName string
	// ConvName/PublicName are the emitted function identifiers; they
	// carry a disambiguating suffix when two pairs would collide.
	ConvName   string
	PublicName string
}

// FieldMap is one src->dst field write inside a generated converter.
// SrcName/DstName are dotted field paths relative to the src/dst
// variables; SrcChain/DstChain hold the resolved FieldInfo per path
// segment (leaf last), so pointer intermediates can be guarded.
type FieldMap struct {
	SrcName   string
	DstName   string
	Converter string // c.Convert's explicit converter func, or ""
	SrcChain  []model.FieldInfo
	DstChain  []model.FieldInfo
	SrcFieldT *xinspect.TypeExpr // leaf source field type
	DstFieldT *xinspect.TypeExpr // leaf destination field type
	// Assign is the emitted assignment block, computed in the emit
	// pass (converter call, rule call, or generated conversion,
	// wrapped in the nil guards/inits nested paths need).
	Assign string
}

// funcNamer maps a "src-decl -> dst-decl" key to the emitted
// converter identifier, so call sites stay consistent when a suffix
// was needed to disambiguate colliding names.
type funcNamer map[string]string

func (fn funcNamer) call(srcElem, dstElem *xinspect.Decl) string {
	if name, ok := fn[model.DeclKey(srcElem)+" -> "+model.DeclKey(dstElem)]; ok {
		return name
	}
	return fmt.Sprintf("convert%sTo%s", srcElem.Name, dstElem.Name)
}

// declNameOf resolves a type expr to the name of the decl it names.
func declNameOf(res xinspect.Resolver, te *xinspect.TypeExpr) string {
	d, err := model.ResolveNamed(res, te)
	if err != nil || d == nil {
		return ""
	}
	return d.Name
}

// isPtr reports whether the declared type is a pointer.
func isPtr(te *xinspect.TypeExpr) bool {
	return te != nil && te.Kind == "StarExpr"
}

// isSlice reports whether the declared type is a slice — `[]T` or
// `...T`. Arrays (`[N]T`, ArrayType with a Len) are handled separately
// since their length is part of the type.
func isSlice(te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	if te.Kind == "Ellipsis" {
		return true
	}
	if at, ok := te.Expr().(*ast.ArrayType); ok {
		return at.Len == nil
	}
	return false
}

// isArray reports whether the declared type is a fixed-length array.
func isArray(te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	at, ok := te.Expr().(*ast.ArrayType)
	return ok && at.Len != nil
}

// isMap reports whether the declared type is a map.
func isMap(te *xinspect.TypeExpr) bool {
	return te != nil && te.Kind == "MapType"
}

// elem returns the element type of a pointer/slice/chan expr, or nil.
func elem(te *xinspect.TypeExpr) *xinspect.TypeExpr {
	if te == nil {
		return nil
	}
	cs := te.Children()
	if len(cs) == 0 {
		return nil
	}
	return cs[len(cs)-1]
}

// mapKeyElem returns the key type of a map expr, or nil.
func mapKeyElem(te *xinspect.TypeExpr) *xinspect.TypeExpr {
	k, _ := mapParts(te)
	return k
}

// mapParts returns the key and element type of a map expr.
func mapParts(te *xinspect.TypeExpr) (k, v *xinspect.TypeExpr) {
	if te == nil {
		return nil, nil
	}
	cs := te.Children()
	if len(cs) != 2 {
		return nil, nil
	}
	return cs[0], cs[1]
}

// isStructType reports whether the type expr resolves to a struct decl.
// Host pseudo-decls (bound stdlib types, e.g. time.Time) and alias decls
// to non-structs all report false — the role IsResolvedByConfig played
// in the previous model.
func isStructType(res xinspect.Resolver, te *xinspect.TypeExpr) bool {
	d, err := model.ResolveNamed(res, te)
	if err != nil {
		return false
	}
	return model.IsStructDecl(d)
}

// Options tunes one Generate call.
type Options struct {
	// Header is written right after the "Code generated" line (e.g.
	// a //go:build constraint).
	Header string
	// PackageIdents are the top-level identifiers of the package the
	// generated file joins (see PackageIdents); temporaries avoid them.
	PackageIdents []string
	// Strict turns generation warnings — field pairs whose emitted
	// assignment will not compile — into a *WarningsError.
	Strict bool
}

// WarningsError is returned in Strict mode when a converter carries
// generation warnings. Each entry is "converter: dst.Field: reason".
type WarningsError struct {
	Warnings []string
}

func (e *WarningsError) Error() string {
	var b strings.Builder
	fmt.Fprintf(&b, "-strict: %d field pair(s) would not compile; no output was written. Fix the define file or the types: add a define.Rule for the type pair, or c.Convert the field with a converter function.\n", len(e.Warnings))
	for _, w := range e.Warnings {
		b.WriteString("  - " + w + "\n")
	}
	return b.String()
}

// baseImports are the packages the generated code's skeleton uses
// (path -> alias).
var baseImports = map[string]string{
	"context": "context",
	"errors":  "errors",
	"fmt":     "fmt",
	"github.com/podhmo/minigo/examples/convert-define/model": "model",
}

func Generate(res xinspect.Resolver, info *model.ParsedInfo, opts Options) ([]byte, error) {
	im := NewImportManager(info.PackagePath)
	ctx := context.Background()

	// The generated code always may use these; registering them first
	// keeps their aliases stable and pushes a user package with the same
	// name to another alias. goimports drops the unused ones.
	for path, alias := range baseImports {
		im.Add(path, alias)
	}

	// Pre-register all necessary imports
	for alias, path := range info.Imports {
		im.Add(path, alias)
	}

	worklist := make([]model.ConversionPair, 0, len(info.ConversionPairs))
	processed := make(map[string]bool)
	allPairs := make([]TemplatePair, 0, len(info.ConversionPairs))

	// Initial population from explicit @derivingconvert annotations
	for _, pair := range info.ConversionPairs {
		key := model.DeclKey(pair.SrcTypeInfo) + " -> " + model.DeclKey(pair.DstTypeInfo)
		if !processed[key] {
			worklist = append(worklist, pair)
			processed[key] = true
		}
	}

	for i := 0; i < len(worklist); i++ {
		pair := worklist[i]

		// Explicit pairs carry their StructInfo already; discovered
		// pairs only know their decls, so materialize the StructInfo
		// here — the same code path as the interpreter's ensureStructInfo.
		srcStruct, err := structInfoFor(info, pair.SrcTypeInfo)
		if err != nil {
			slog.WarnContext(ctx, "source struct for conversion not found in parsed info, skipping", "type", model.DeclKey(pair.SrcTypeInfo), "error", err)
			continue
		}
		dstStruct, err := structInfoFor(info, pair.DstTypeInfo)
		if err != nil {
			slog.WarnContext(ctx, "destination struct for conversion not found in parsed info, skipping", "type", model.DeclKey(pair.DstTypeInfo), "error", err)
			continue
		}

		// Register imports for the current pair's types
		for _, field := range srcStruct.Fields {
			registerImports(im, field.FieldType)
		}
		for _, field := range dstStruct.Fields {
			registerImports(im, field.FieldType)
		}

		fieldMaps, unmappedFields, err := createFieldMaps(ctx, res, info, srcStruct, dstStruct, &pair)
		if err != nil {
			return nil, fmt.Errorf("creating field maps for %s -> %s: %w", srcStruct.Name, dstStruct.Name, err)
		}

		// Discover new pairs from fields — element types plus, for map
		// fields, key types (StructElemOf follows only the value side).
		for _, fm := range fieldMaps {
			typePairs := [][2]*xinspect.TypeExpr{{fm.SrcFieldT, fm.DstFieldT}}
			if sk, dk := mapKeyElem(fm.SrcFieldT), mapKeyElem(fm.DstFieldT); sk != nil && dk != nil {
				typePairs = append(typePairs, [2]*xinspect.TypeExpr{sk, dk})
			}
			for _, tp := range typePairs {
				srcFieldType := model.StructElemOf(res, tp[0])
				dstFieldType := model.StructElemOf(res, tp[1])

				if srcFieldType != nil && dstFieldType != nil {
					key := model.DeclKey(srcFieldType) + " -> " + model.DeclKey(dstFieldType)
					if !processed[key] {
						slog.DebugContext(ctx, "Discovered required conversion", "key", key)
						newPair := model.ConversionPair{
							SrcTypeName: srcFieldType.Name,
							DstTypeName: dstFieldType.Name,
							SrcTypeInfo: srcFieldType,
							DstTypeInfo: dstFieldType,
						}
						worklist = append(worklist, newPair)
						processed[key] = true
					}
				}
			}
		}

		allPairs = append(allPairs, TemplatePair{
			SrcType:        srcStruct,
			DstType:        dstStruct,
			Fields:         fieldMaps,
			Pair:           pair,
			UnmappedFields: unmappedFields,
		})
	}

	// Assign function names after the worklist: pairs that would emit
	// the same converter identifier (e.g. a.User -> b.User and
	// a.User -> c.User) get a deterministic disambiguating suffix.
	funcNames := funcNamer{}
	taken := map[string]bool{}
	for i := range allPairs {
		tp := &allPairs[i]
		base := fmt.Sprintf("%sTo%s", tp.SrcType.Name, tp.DstType.Name)
		name := base
		if taken["convert"+name] {
			name = base + "From" + sanitizeIdent(filepath.Base(tp.SrcType.Type.Package.Path)) + "To" + sanitizeIdent(filepath.Base(tp.DstType.Type.Package.Path))
		}
		for n := 2; taken["convert"+name]; n++ {
			name = fmt.Sprintf("%s%d", base, n)
		}
		taken["convert"+name] = true
		tp.ConvName = "convert" + name
		tp.PublicName = "Convert" + name
		funcNames[model.DeclKey(tp.Pair.SrcTypeInfo)+" -> "+model.DeclKey(tp.Pair.DstTypeInfo)] = tp.ConvName
	}

	// Emit pass: assignment text for every field map is computed here
	// (converter calls, rule calls, generated conversions, and the nil
	// guards/inits nested paths need) so template execution is pure
	// formatting. Leaf-pair mismatches collect as warnings on the pair.
	for i := range allPairs {
		tp := &allPairs[i]
		// Qualifying registers the import, so it must happen here —
		// before the Imports snapshot — not during template execution.
		tp.SrcTypeName = qualifiedStructName(im, info, tp.SrcType)
		tp.DstTypeName = qualifiedStructName(im, info, tp.DstType)
		diag := newGenDiags()
		e := newEmitter(im, res, info, funcNames, diag, tp, opts.PackageIdents)
		for j := range tp.Fields {
			tp.Fields[j].Assign = e.assignment(tp.Fields[j], "src", "dst")
		}
		for j := range tp.Pair.Computed {
			chain, err := model.ResolveFieldPath(info, res, tp.DstType, tp.Pair.Computed[j].DstName)
			if err != nil {
				return nil, fmt.Errorf("computing %s -> %s field %s: %w", tp.SrcType.Name, tp.DstType.Name, tp.Pair.Computed[j].DstName, err)
			}
			tp.Pair.Computed[j].Prelude = dstInits(im, chain, "dst")
			if c := tp.Pair.Computed[j]; c.ExprType != nil && len(chain) > 0 {
				if m := computeMismatch(im, res, c.Expr, c.ExprType, chain[len(chain)-1].FieldType); m != "" {
					diag.at("dst." + c.DstName).warn(m)
				}
			}
		}
		tp.Warnings = diag.warnings()
		for _, w := range tp.Warnings {
			slog.WarnContext(ctx, w, "converter", tp.ConvName)
		}
	}
	if opts.Strict {
		var all []string
		for _, tp := range allPairs {
			for _, w := range tp.Warnings {
				all = append(all, tp.ConvName+": "+w)
			}
		}
		if len(all) > 0 {
			return nil, &WarningsError{Warnings: all}
		}
	}

	for _, rule := range info.GlobalRules {
		if rule.SrcTypeInfo != nil && rule.SrcTypeInfo.Package != nil {
			im.Qualify(rule.SrcTypeInfo.Package.Path, rule.SrcTypeInfo.Name)
		}
		if rule.DstTypeInfo != nil && rule.DstTypeInfo.Package != nil {
			im.Qualify(rule.DstTypeInfo.Package.Path, rule.DstTypeInfo.Name)
		}
	}

	templateData := TemplateData{
		PackageName: info.PackageName,
		Imports:     im.Imports(),
		Pairs:       allPairs,
		Header:      opts.Header,
	}

	tmpl, err := template.New("converter").Parse(codeTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	return buf.Bytes(), nil
}

// qualifiedStructName spells a struct type in the generated file's
// terms; types of the generated package itself stay unqualified.
func qualifiedStructName(im *ImportManager, info *model.ParsedInfo, si *model.StructInfo) string {
	if si == nil || si.Type == nil || si.Type.Package == nil {
		return "invalid"
	}
	if si.Type.Package.Path == info.PackagePath && info.PackagePath != "" {
		return si.Name
	}
	return im.Qualify(si.Type.Package.Path, si.Name)
}

// structInfoFor returns the StructInfo for a conversion decl,
// materializing it from the decl when the interpreter's pass did not
// (the common case for types discovered through field traversal).
func structInfoFor(info *model.ParsedInfo, d *xinspect.Decl) (*model.StructInfo, error) {
	key := model.DeclKey(d)
	if si, ok := info.Structs[key]; ok {
		return si, nil
	}
	si, err := model.StructInfoFromDecl(d)
	if err != nil {
		return nil, err
	}
	info.Structs[key] = si
	return si, nil
}

// sanitizeIdent renders a package path as an identifier-safe fragment
// for converter-name disambiguation ("a/b/c" -> "abc").
func sanitizeIdent(path string) string {
	var b strings.Builder
	for _, r := range path {
		if r == '_' || r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func createFieldMaps(ctx context.Context, res xinspect.Resolver, info *model.ParsedInfo, src, dst *model.StructInfo, pair *model.ConversionPair) ([]FieldMap, []string, error) {
	var maps []FieldMap
	dstFieldsByNormalizedJSONTag := make(map[string]model.FieldInfo)
	dstFieldsByNormalizedName := make(map[string]model.FieldInfo)
	unmappedDstFields := make(map[string]bool)
	// Top-level src fields claimed by an explicit c.Map/c.Convert —
	// name/json matching must not double-assign them.
	consumedSrcFields := make(map[string]bool)

	slog.DebugContext(ctx, "Destination struct", "name", dst.Name)
	for _, f := range dst.Fields {
		if f.JSONTag != "" && f.JSONTag != "-" {
			normalized := normalizeFieldName(f.JSONTag)
			dstFieldsByNormalizedJSONTag[normalized] = f
			slog.DebugContext(ctx, "dst field", "name", f.Name, "json", f.JSONTag, "normalized_json", normalized)
		}
		normalized := normalizeFieldName(f.Name)
		dstFieldsByNormalizedName[normalized] = f
		slog.DebugContext(ctx, "dst field", "name", f.Name, "normalized_name", normalized)
		unmappedDstFields[f.Name] = true
	}

	// Explicit c.Map/c.Convert entries. Both sides were already
	// validated by the walker; here they resolve again to leaf types.
	// A nested src path leaves its top field available for matching;
	// a plain field name claims it.
	var explicit []FieldMap
	// claimedDstFields are top-level dst fields an explicit mapping or
	// c.Compute writes as a whole; auto-matching them would emit a dead
	// (and possibly ill-typed) assignment that is then overwritten.
	claimedDstFields := make(map[string]bool)
	if pair.Mapping != nil {
		for _, m := range pair.Mapping.Maps {
			srcChain, err := model.ResolveFieldPath(info, res, src, m.SrcName)
			if err != nil {
				return nil, nil, fmt.Errorf("mapping %s -> %s: %w", m.SrcName, m.DstName, err)
			}
			dstChain, err := model.ResolveFieldPath(info, res, dst, m.DstName)
			if err != nil {
				return nil, nil, fmt.Errorf("mapping %s -> %s: %w", m.SrcName, m.DstName, err)
			}
			if !strings.Contains(m.SrcName, ".") {
				consumedSrcFields[m.SrcName] = true
			}
			if !strings.Contains(m.DstName, ".") {
				claimedDstFields[m.DstName] = true
			}
			delete(unmappedDstFields, firstSeg(m.DstName))
			explicit = append(explicit, FieldMap{
				SrcName:   m.SrcName,
				DstName:   m.DstName,
				Converter: m.Converter,
				SrcChain:  srcChain,
				DstChain:  dstChain,
				SrcFieldT: srcChain[len(srcChain)-1].FieldType,
				DstFieldT: dstChain[len(dstChain)-1].FieldType,
			})
		}
	}

	// Remove computed fields from the unmapped list (a nested compute
	// destination counts its top-level field as populated).
	for _, computed := range pair.Computed {
		if !strings.Contains(computed.DstName, ".") {
			claimedDstFields[computed.DstName] = true
		}
		delete(unmappedDstFields, firstSeg(computed.DstName))
	}

	slog.DebugContext(ctx, "Source struct", "name", src.Name)
	for _, srcField := range src.Fields {
		if consumedSrcFields[srcField.Name] {
			slog.DebugContext(ctx, "src field claimed by explicit mapping", "name", srcField.Name)
			continue
		}

		var dstField model.FieldInfo
		var ok bool
		var reason string

		// Priority 1: Normalized `json` tag
		if srcField.JSONTag != "" && srcField.JSONTag != "-" {
			normalizedJSONTag := normalizeFieldName(srcField.JSONTag)
			dstField, ok = dstFieldsByNormalizedJSONTag[normalizedJSONTag]
			reason = fmt.Sprintf("normalized `json` tag (%s -> %s)", srcField.JSONTag, normalizedJSONTag)
		}

		// Priority 2: Normalized field name
		if !ok {
			normalizedSrcName := normalizeFieldName(srcField.Name)
			dstField, ok = dstFieldsByNormalizedName[normalizedSrcName]
			reason = fmt.Sprintf("normalized name (%s -> %s)", srcField.Name, normalizedSrcName)
		}

		if !ok {
			slog.DebugContext(ctx, "src field no match found", "name", srcField.Name)
			continue
		}

		if claimedDstFields[dstField.Name] {
			slog.DebugContext(ctx, "dst field claimed by explicit mapping or compute", "src", srcField.Name, "dst", dstField.Name)
			continue
		}

		slog.DebugContext(ctx, "src field matched", "src", srcField.Name, "dst", dstField.Name, "reason", reason)
		delete(unmappedDstFields, dstField.Name)
		maps = append(maps, FieldMap{
			SrcName:   srcField.Name,
			DstName:   dstField.Name,
			SrcChain:  []model.FieldInfo{srcField},
			DstChain:  []model.FieldInfo{dstField},
			SrcFieldT: srcField.FieldType,
			DstFieldT: dstField.FieldType,
		})
	}

	// Explicit maps emit last, so a leaf-path mapping overrides the
	// whole-struct auto assignment of a shared ancestor (e.g.
	// c.Map(dst.Inner.ID, src.ID) after dst.Inner = convert(src.Inner)).
	maps = append(maps, explicit...)

	// Collect unmapped fields
	var unmapped []string
	for fieldName := range unmappedDstFields {
		unmapped = append(unmapped, fieldName)
	}
	// sort for deterministic output
	slices.Sort(unmapped)

	return maps, unmapped, nil
}

// firstSeg returns the first segment of a field path ("Inner.ID" -> "Inner").
func firstSeg(path string) string {
	if i := strings.IndexByte(path, '.'); i >= 0 {
		return path[:i]
	}
	return path
}

func normalizeFieldName(name string) string {
	return strings.ToLower(strings.ReplaceAll(name, "_", ""))
}

func qualifyFunc(im *ImportManager, info *model.ParsedInfo, funcName string) string {
	parts := strings.Split(funcName, ".")
	if len(parts) != 2 {
		return funcName // Not a qualified function name, assume it's in the current package
	}
	alias, name := parts[0], parts[1]
	path, ok := info.Imports[alias]
	if !ok {
		slog.Warn("could not find import path for alias in function", "alias", alias, "funcName", funcName)
		return funcName
	}
	finalAlias := im.Add(path, alias)
	return finalAlias + "." + name
}

// registerImports qualifies every named type reachable through the
// TypeExpr — pointers, slices, maps, func types, and generic
// instantiation bases (pkg.List in pkg.List[T]), which Children() does
// not yield and so are reached via Sub.
func registerImports(im *ImportManager, te *xinspect.TypeExpr) {
	if te == nil {
		return
	}
	if sid, ok := te.SymbolID(); ok {
		if sid.PackagePath != xinspect.BuiltinPackagePath {
			im.Qualify(sid.PackagePath, sid.Name)
		}
		return
	}
	switch e := te.Expr().(type) {
	case *ast.IndexExpr:
		registerImports(im, te.Sub(e.X))
	case *ast.IndexListExpr:
		registerImports(im, te.Sub(e.X))
	}
	for _, c := range te.Children() {
		registerImports(im, c)
	}
}

// -----------------------------------------------------------------------------
// Assignment Logic
// -----------------------------------------------------------------------------

type ruleMatchResult struct {
	Rule           *model.TypeRule
	IsPointerMatch bool
}

func findMatchingRule(info *model.ParsedInfo, srcT, dstT *xinspect.TypeExpr) *ruleMatchResult {
	if srcT == nil || dstT == nil {
		return nil
	}

	srcFieldTypeName := srcT.CanonicalName()
	dstFieldTypeName := dstT.CanonicalName()

	for i := range info.GlobalRules {
		rule := &info.GlobalRules[i]
		if rule.UsingFunc == "" {
			continue
		}

		if rule.SrcTypeName == srcFieldTypeName && rule.DstTypeName == dstFieldTypeName {
			// Determine if it's a pointer match based on the source field type.
			// This is simpler than trying to infer from the rule's TypeInfo.
			return &ruleMatchResult{Rule: rule, IsPointerMatch: isPtr(srcT)}
		}
	}

	return nil
}

// -----------------------------------------------------------------------------
// Conversion fragments
// -----------------------------------------------------------------------------

// frag is one converted value: stmts must run first, after which expr
// holds the value. Every shape (pointer, slice, array, map, struct,
// leaf) is implemented once as a frag; the parent decides where it
// lands — a field assignment, a loop body, or a nil-guarded block.
//
// Invariants that keep this sound without a scope tracker:
//   - stmts are placed in the same block as the use of expr, right
//     before it. Control flow (nil guards, loops) is owned by the parent
//     that builds that block, so a child's stmts never run outside the
//     guard or loop iteration its expr belongs to.
//   - temporaries come from emitter.fresh, which skips every identifier
//     visible inside the converter (see newEmitter), so hoisted names
//     neither collide nor shadow.
type frag struct {
	stmts []string
	expr  string
}

func pure(expr string) frag { return frag{expr: expr} }

// assign renders f as statements writing its value into dst.
func (f frag) assign(dst string) []string {
	return slices.Concat(f.stmts, []string{dst + " = " + f.expr})
}

// block renders `head { body }` ("{ body }" for an empty head); the
// generated file is gofmt'd afterwards, so indentation is not tracked.
func block(head string, body ...string) string {
	if head != "" {
		head += " "
	}
	return head + "{\n" + strings.Join(body, "\n") + "\n}"
}

// emitter carries what every conversion step needs for one converter
// function, plus that function's temporary-name allocator.
type emitter struct {
	im     *ImportManager
	res    xinspect.Resolver
	info   *model.ParsedInfo
	fn     funcNamer
	diag   *genDiags
	taken  map[string]bool
	ctxVar string
	ecVar  string
}

// newEmitter reserves every identifier visible inside the converter
// body: its parameters and locals, the generated package's own
// top-level identifiers, the fixed imports, and the unqualified (same-package) rule and converter
// funcs. Import aliases are checked at allocation time (fresh) because
// the ImportManager keeps growing during the emit pass.
func newEmitter(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, diag *genDiags, pair *TemplatePair, packageIdents []string) *emitter {
	taken := map[string]bool{"ctx": true, "ec": true, "src": true, "dst": true, "context": true, "errors": true, "fmt": true, "model": true}
	for _, id := range packageIdents {
		taken[id] = true
	}
	for _, r := range info.GlobalRules {
		taken[r.UsingFunc] = true
	}
	for _, f := range pair.Fields {
		taken[f.Converter] = true
	}
	return &emitter{im: im, res: res, info: info, fn: fn, diag: diag, taken: taken, ctxVar: "ctx", ecVar: "ec"}
}

// fresh returns prefix, prefix2, prefix3, ... — the first spelling not
// already visible in the converter.
func (e *emitter) fresh(prefix string) string {
	aliases := map[string]bool{}
	for _, a := range e.im.Imports() {
		aliases[a] = true
	}
	name := prefix
	for n := 2; e.taken[name] || aliases[name]; n++ {
		name = fmt.Sprintf("%s%d", prefix, n)
	}
	e.taken[name] = true
	return name
}

// assignment renders one field write. For nested paths the write is
// preceded by dst-side nil inits (pointer intermediates must exist
// before their leaf is written) and wrapped in src-side nil guards (a
// nil pointer intermediate means "no value to copy"). A write that
// needs temporaries gets its own block, so they stay local to the field.
func (e *emitter) assignment(field FieldMap, srcVar, dstVar string) string {
	src := fmt.Sprintf("%s.%s", srcVar, field.SrcName)
	dst := fmt.Sprintf("%s.%s", dstVar, field.DstName)

	// Temporaries are local to this field's block, so numbering
	// restarts per field.
	reserved := maps.Clone(e.taken)
	defer func() { e.taken = reserved }()

	var f frag
	switch {
	// Priority 1: field-level converter (c.Convert)
	case field.Converter != "":
		f = e.call(field.Converter, src)
	default:
		// Priority 2: global conversion rule; Priority 3: default
		// conversion logic — warnings are labelled with the
		// destination path of this field.
		saved := e.diag
		e.diag = e.diag.at(dst)
		f = e.conv(src, field.SrcFieldT, field.DstFieldT)
		e.diag = saved
	}

	body := strings.Join(f.assign(dst), "\n")
	if len(f.stmts) > 0 && !hasPtrIntermediate(field.SrcChain) {
		body = block("", body)
	}
	return srcGuardWrap(dstInits(e.im, field.DstChain, dstVar)+body, field.SrcChain, srcVar)
}

// call invokes a user-provided func with the (ctx, ec, src) contract.
func (e *emitter) call(funcName, src string) frag {
	return pure(fmt.Sprintf("%s(%s, %s, %s)", qualifyFunc(e.im, e.info, funcName), e.ctxVar, e.ecVar, src))
}

// conv converts src, an expression of type srcT, into a value of dstT.
func (e *emitter) conv(src string, srcT, dstT *xinspect.TypeExpr) frag {
	// Global conversion rule — the user-provided function is expected
	// to have the correct signature (e.g., handle pointers correctly).
	if match := findMatchingRule(e.info, srcT, dstT); match != nil {
		return e.call(match.Rule.UsingFunc, src)
	}

	if srcT == nil || dstT == nil {
		e.diag.warn(fmt.Sprintf("unresolved field type for %s", src))
		return pure(src)
	}

	// Identical value types assign directly — same-name structs, same
	// scalars, etc. Pointers, slices and maps are excluded: they fall
	// through to the shape branches below, which allocate fresh copies
	// instead of aliasing the source's memory.
	if srcT.SameType(dstT, e.res) && !isPtr(srcT) && !isSlice(srcT) && !isMap(srcT) {
		return pure(src)
	}

	switch {
	case isPtr(srcT) && isPtr(dstT):
		return e.ptrToPtr(src, srcT, dstT)
	case isPtr(srcT):
		return e.ptrToValue(src, srcT, dstT)
	case isPtr(dstT):
		return e.valueToPtr(src, srcT, dstT)
	case isSlice(srcT) && isSlice(dstT):
		return e.slice(src, srcT, dstT)
	// Arrays: fixed-length; element conversion proceeds one index at a
	// time (same-type arrays already assigned above).
	case isArray(srcT) && isArray(dstT):
		return e.array(src, srcT, dstT)
	case isMap(srcT) && isMap(dstT):
		return e.mapOf(src, srcT, dstT)
	}

	// Structs
	srcDecl, dstDecl := namedDeclOf(e.res, srcT), namedDeclOf(e.res, dstT)
	if model.IsStructDecl(srcDecl) && model.IsStructDecl(dstDecl) {
		srcPtr := src
		if !isPtr(srcT) {
			srcPtr = "&" + src
		}
		return pure(fmt.Sprintf("*%s(%s, %s, %s)", e.fn.call(srcDecl, dstDecl), e.ctxVar, e.ecVar, srcPtr))
	}

	// Basic assignment — with a type conversion when the canonical names
	// differ but the shape is castable (named leaf types, numeric pairs).
	// When neither applies the raw assignment is kept (it is what the
	// compiler sees), but the mismatch is reported as a generation
	// warning instead of failing silently at compile time.
	if cast, ok := leafCast(e.im, e.res, srcT, dstT, src); ok {
		return pure(cast)
	}
	e.diag.warn(leafMismatch(e.im, e.res, srcT, dstT))
	return pure(src)
}

func (e *emitter) ptrToPtr(src string, srcT, dstT *xinspect.TypeExpr) frag {
	srcElem, dstElem := elem(srcT), elem(dstT)
	if srcElem == nil || dstElem == nil {
		// Fallback for unresolved types or built-in pointers like *int
		return pure(src)
	}
	// If the elements are structs that have a dedicated converter, use
	// it directly — but only at exactly one level of indirection:
	// `**T` is not a `*T` argument.
	srcElemDecl, dstElemDecl := namedDeclOf(e.res, srcElem), namedDeclOf(e.res, dstElem)
	if !isPtr(srcElem) && !isPtr(dstElem) && model.IsStructDecl(srcElemDecl) && model.IsStructDecl(dstElemDecl) {
		return pure(fmt.Sprintf("%s(%s, %s, %s)", e.fn.call(srcElemDecl, dstElemDecl), e.ctxVar, e.ecVar, src))
	}
	out, v := e.fresh("p"), e.fresh("v")
	inner := e.conv("(*"+src+")", srcElem, dstElem)
	return frag{
		stmts: []string{
			fmt.Sprintf("var %s %s", out, getTypeName(e.im, dstT)),
			block(fmt.Sprintf("if %s != nil", src), slices.Concat(inner.stmts, []string{v + " := " + inner.expr, out + " = &" + v})...),
		},
		expr: out,
	}
}

// ptrToValue dereferences under a nil guard; nil yields the zero value.
func (e *emitter) ptrToValue(src string, srcT, dstT *xinspect.TypeExpr) frag {
	srcElem := elem(srcT)
	if srcElem == nil {
		e.diag.warn(fmt.Sprintf("cannot convert pointer to value: unresolved element type of %s", src))
		return pure(src)
	}
	out := e.fresh("v")
	inner := e.conv("(*"+src+")", srcElem, dstT)
	return frag{
		stmts: []string{
			fmt.Sprintf("var %s %s", out, getTypeName(e.im, dstT)),
			block(fmt.Sprintf("if %s != nil", src), inner.assign(out)...),
		},
		expr: out,
	}
}

func (e *emitter) valueToPtr(src string, srcT, dstT *xinspect.TypeExpr) frag {
	dstElem := elem(dstT)
	if dstElem == nil {
		e.diag.warn(fmt.Sprintf("cannot convert value to pointer: unresolved element type of %s", src))
		return pure(src)
	}
	v := e.fresh("v")
	inner := e.conv(src, srcT, dstElem)
	return frag{stmts: slices.Concat(inner.stmts, []string{v + " := " + inner.expr}), expr: "&" + v}
}

// loopBody renders one element step: the error-path segment around the
// element's own stmts and its write.
func (e *emitter) loopBody(segFormat, segVar string, el frag, write string) []string {
	return slices.Concat(
		[]string{fmt.Sprintf("%s.Enter(fmt.Sprintf(%q, %s))", e.ecVar, segFormat, segVar)},
		el.stmts,
		[]string{write + " = " + el.expr, e.ecVar + ".Leave()"},
	)
}

func (e *emitter) slice(src string, srcT, dstT *xinspect.TypeExpr) frag {
	srcElem, dstElem := elem(srcT), elem(dstT)
	if srcElem == nil || dstElem == nil {
		e.diag.warn(fmt.Sprintf("unresolved slice element type of %s", src))
		return pure(src)
	}
	out, i, item := e.fresh("s"), e.fresh("i"), e.fresh("item")
	el := e.conv(item, srcElem, dstElem)
	return frag{
		stmts: []string{
			fmt.Sprintf("%s := make([]%s, len(%s))", out, getTypeName(e.im, dstElem), src),
			block(fmt.Sprintf("for %s, %s := range %s", i, item, src), e.loopBody("[%d]", i, el, out+"["+i+"]")...),
		},
		expr: out,
	}
}

func (e *emitter) array(src string, srcT, dstT *xinspect.TypeExpr) frag {
	srcElem, dstElem := elem(srcT), elem(dstT)
	if srcElem == nil || dstElem == nil {
		e.diag.warn(fmt.Sprintf("unresolved array element type of %s", src))
		return pure(src)
	}
	out, i, item := e.fresh("a"), e.fresh("i"), e.fresh("item")
	el := e.conv(item, srcElem, dstElem)
	return frag{
		stmts: []string{
			fmt.Sprintf("var %s %s", out, getTypeName(e.im, dstT)),
			block(fmt.Sprintf("for %s, %s := range %s", i, item, src), e.loopBody("[%d]", i, el, out+"["+i+"]")...),
		},
		expr: out,
	}
}

func (e *emitter) mapOf(src string, srcT, dstT *xinspect.TypeExpr) frag {
	srcKT, srcVT := mapParts(srcT)
	dstKT, dstVT := mapParts(dstT)
	if srcKT == nil || srcVT == nil || dstKT == nil || dstVT == nil {
		e.diag.warn(fmt.Sprintf("unresolved map key/value type of %s", src))
		return pure(src)
	}
	out, key, value := e.fresh("m"), e.fresh("key"), e.fresh("value")
	k := pure(key)
	if !srcKT.SameType(dstKT, e.res) {
		k = e.conv(key, srcKT, dstKT)
	}
	v := e.conv(value, srcVT, dstVT)
	// The key's stmts run with the value's, inside the same iteration.
	el := frag{stmts: slices.Concat(k.stmts, v.stmts), expr: v.expr}
	return frag{
		stmts: []string{
			fmt.Sprintf("%s := make(map[%s]%s, len(%s))", out, getTypeName(e.im, dstKT), getTypeName(e.im, dstVT), src),
			block(fmt.Sprintf("for %s, %s := range %s", key, value, src), e.loopBody("[%v]", key, el, out+"["+k.expr+"]")...),
		},
		expr: out,
	}
}

// chainPath renders the first n segments of a resolved field chain
// joined by "." — the access path of the n-th field.
func chainPath(chain []model.FieldInfo, n int) string {
	parts := make([]string, n)
	for i := 0; i < n; i++ {
		parts[i] = chain[i].Name
	}
	return strings.Join(parts, ".")
}

// dstInits emits `if p == nil { p = &T{} }` for every pointer
// intermediate in a destination path, so writes into `dst.In.X`
// cannot panic. Depth-1 chains emit nothing.
func dstInits(im *ImportManager, chain []model.FieldInfo, dstVar string) string {
	var b strings.Builder
	for i := 0; i+1 < len(chain); i++ {
		ft := chain[i].FieldType
		if !isPtr(ft) {
			continue
		}
		p := dstVar + "." + chainPath(chain, i+1)
		fmt.Fprintf(&b, "if %s == nil {\n\t%s = &%s{}\n}\n", p, p, getTypeName(im, elem(ft)))
	}
	return b.String()
}

// hasPtrIntermediate reports whether srcGuardWrap would add a guard.
func hasPtrIntermediate(chain []model.FieldInfo) bool {
	for i := 0; i+1 < len(chain); i++ {
		if isPtr(chain[i].FieldType) {
			return true
		}
	}
	return false
}

// srcGuardWrap nests body inside `if p != nil {}` for every pointer
// intermediate in a source path — outermost guard outermost. Depth-1
// chains return body unchanged.
func srcGuardWrap(body string, chain []model.FieldInfo, srcVar string) string {
	for i := len(chain) - 2; i >= 0; i-- {
		if !isPtr(chain[i].FieldType) {
			continue
		}
		p := srcVar + "." + chainPath(chain, i+1)
		body = fmt.Sprintf("if %s != nil {\n%s\n}", p, indentLines(body))
	}
	return body
}

// indentLines prefixes each non-empty line with a tab — emitted code
// is normalized by goimports afterwards, this only keeps the raw text
// readable.
func indentLines(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = "\t" + l
		}
	}
	return strings.Join(lines, "\n")
}

// genDiags accumulates generate-time warnings for one converter —
// leaf pairs that fall back to a raw assignment between incompatible
// types. The generated code still emits the assignment (it is the
// honest output); the warning surfaces in the doc comment and via
// slog so the failure is visible before compile time.
type genDiags struct {
	site  string // label prepended to each warning (the dst field path)
	items *[]string
	seen  map[string]bool
}

func newGenDiags() *genDiags {
	return &genDiags{items: new([]string), seen: map[string]bool{}}
}

// at returns a view that labels every warning with the given site.
func (d *genDiags) at(site string) *genDiags {
	return &genDiags{site: site, items: d.items, seen: d.seen}
}

// warn records a warning, prefixed by the site label and deduplicated.
func (d *genDiags) warn(msg string) {
	if msg == "" {
		return
	}
	if d.site != "" {
		msg = d.site + ": " + msg
	}
	if d.seen[msg] {
		return
	}
	d.seen[msg] = true
	*d.items = append(*d.items, msg)
}

func (d *genDiags) warnings() []string {
	return *d.items
}

// leafMismatch describes a leaf src/dst pair that no rule, cast, or
// shape branch covers — the raw assignment that follows will not
// compile. Returns "" when the pair is safely assignable after all
// (dst accepts any value, or a named src may satisfy a dst interface).
func leafMismatch(im *ImportManager, res xinspect.Resolver, srcT, dstT *xinspect.TypeExpr) string {
	if isEmptyIface(res, dstT) {
		return ""
	}
	// A non-empty interface dst is satisfied whenever the src is a
	// named type that could carry the methods — without go/types that
	// cannot be verified, so stay quiet rather than cry wolf.
	if isIfaceDecl(namedDeclOf(res, dstT)) {
		if sid, ok := srcT.Unref().SymbolID(); ok && sid.PackagePath != xinspect.BuiltinPackagePath {
			return ""
		}
	}
	return fmt.Sprintf("no conversion covers %s -> %s", getTypeName(im, srcT), getTypeName(im, dstT))
}

// computeMismatch describes a c.Compute expression whose inferred type
// the destination field cannot hold. The expression is emitted as the
// user wrote it (no cast), so anything short of an identical or safely
// assignable type will not compile. An unnamed composite and a named
// type may still be assignable through their underlying type, which
// cannot be checked without go/types — that case stays quiet.
func computeMismatch(im *ImportManager, res xinspect.Resolver, expr string, exprT, dstT *xinspect.TypeExpr) string {
	if exprT.SameType(dstT, res) {
		return ""
	}
	if isUnnamed(exprT) != isUnnamed(dstT) {
		return ""
	}
	if leafMismatch(im, res, exprT, dstT) == "" {
		return ""
	}
	msg := fmt.Sprintf("c.Compute expression %s is %s, not %s", expr, getTypeName(im, exprT), getTypeName(im, dstT))
	if _, ok := leafCast(im, res, exprT, dstT, expr); ok {
		msg += fmt.Sprintf(" (write %s(...) in the define file)", getTypeName(im, dstT))
	}
	return msg
}

// isUnnamed reports whether te is a type literal ([]T, *T, map[K]V,
// ...) rather than a named or predeclared type.
func isUnnamed(te *xinspect.TypeExpr) bool {
	_, named := te.SymbolID()
	return !named
}

// isIfaceDecl reports whether the declaration is a named interface type.
func isIfaceDecl(d *xinspect.Decl) bool {
	if d == nil || d.Kind != "type" {
		return false
	}
	def, err := xinspect.DefOf(d)
	return err == nil && def.Kind == "InterfaceType"
}

// isEmptyIface reports whether the type accepts every value: `any`, a
// literal `interface{}`, or a named type whose decl is an empty
// interface.
func isEmptyIface(res xinspect.Resolver, te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	if sid, ok := te.SymbolID(); ok && sid.PackagePath == xinspect.BuiltinPackagePath && sid.Name == "any" {
		return true
	}
	if it, ok := te.Expr().(*ast.InterfaceType); ok && len(it.Methods.List) == 0 {
		return true
	}
	if d := namedDeclOf(res, te); d != nil {
		if def, err := xinspect.DefOf(d); err == nil {
			if it, ok := def.Expr().(*ast.InterfaceType); ok && len(it.Methods.List) == 0 {
				return true
			}
		}
	}
	return false
}

// namedDeclOf resolves a type expr to its declaration, or nil for
// builtins and composite shapes.
func namedDeclOf(res xinspect.Resolver, te *xinspect.TypeExpr) *xinspect.Decl {
	d, err := model.ResolveNamed(res, te)
	if err != nil {
		return nil
	}
	return d
}

// numericBuiltins is the set of predeclared numeric types — casts
// between them are always legal Go.
var numericBuiltins = map[string]bool{
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
	"uintptr": true, "byte": true, "rune": true,
	"float32": true, "float64": true, "complex64": true, "complex128": true,
}

// leafCast reports the `dstT(src)` cast to emit when src and dst are
// leaf types with different canonical names: either side being a named
// (non-builtin) type that is not itself a struct/interface, or both
// being numeric builtins, makes a plain conversion legal; string <->
// []byte/[]rune converts natively; anything else is left to a raw
// assignment that the compiler will flag if it is truly wrong.
func leafCast(im *ImportManager, res xinspect.Resolver, srcT, dstT *xinspect.TypeExpr, src string) (string, bool) {
	// string <-> []byte / []rune — the only builtin leaf/composite
	// pairs Go can convert directly.
	if isStringLeaf(dstT) && isByteOrRuneSlice(srcT) {
		return fmt.Sprintf("string(%s)", src), true
	}
	if isStringLeaf(srcT) && isByteOrRuneSlice(dstT) {
		return fmt.Sprintf("%s(%s)", getTypeName(im, dstT), src), true
	}

	srcCanon, dstCanon := srcT.CanonicalName(), dstT.CanonicalName()
	if srcCanon == "" || dstCanon == "" || srcCanon == dstCanon {
		return "", false
	}
	// A named type is castable to an unrelated leaf only when its decl
	// is not a struct or interface — `string(time.Time)` does not
	// compile but `string(MyInt)` does. Unresolvable decls keep the
	// previous optimistic behaviour.
	isCastableNamed := func(te *xinspect.TypeExpr) bool {
		sid, ok := te.Unref().SymbolID()
		if !ok || sid.PackagePath == xinspect.BuiltinPackagePath {
			return false
		}
		if d, err := model.ResolveNamed(res, te); err == nil && d != nil {
			if model.IsStructDecl(d) || isIfaceDecl(d) {
				return false
			}
		}
		return true
	}
	if isCastableNamed(dstT) || isCastableNamed(srcT) || (numericBuiltins[srcCanon] && numericBuiltins[dstCanon]) {
		return fmt.Sprintf("%s(%s)", getTypeName(im, dstT), src), true
	}
	return "", false
}

// isStringLeaf reports whether the type is the builtin string type.
func isStringLeaf(te *xinspect.TypeExpr) bool {
	return te != nil && te.CanonicalName() == "string"
}

// isByteOrRuneSlice reports whether the type is []byte/[]uint8 or
// []rune/[]int32 — the slice shapes convertible to and from string.
func isByteOrRuneSlice(te *xinspect.TypeExpr) bool {
	if !isSlice(te) {
		return false
	}
	e := elem(te)
	if e == nil {
		return false
	}
	switch e.CanonicalName() {
	case "byte", "uint8", "rune", "int32":
		return true
	}
	return false
}

// getTypeName renders a TypeExpr in the generated file's terms —
// declared identifiers become im.Qualify'd names; composite shapes that
// carry no resolvable identity (anonymous struct/func types) keep the
// written spelling.
func getTypeName(im *ImportManager, te *xinspect.TypeExpr) string {
	if te == nil {
		return "interface{}" // Should not happen in valid code
	}

	switch e := te.Expr().(type) {
	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", getTypeName(im, te.Sub(e.X)), getTypeName(im, te.Sub(e.Index)))
	case *ast.IndexListExpr:
		var args []string
		for _, ix := range e.Indices {
			args = append(args, getTypeName(im, te.Sub(ix)))
		}
		return fmt.Sprintf("%s[%s]", getTypeName(im, te.Sub(e.X)), strings.Join(args, ","))
	}

	switch {
	case isPtr(te):
		if e := elem(te); e != nil {
			return "*" + getTypeName(im, e)
		}
		return te.Text // te.Text already carries the "*"
	case isArray(te):
		at := te.Expr().(*ast.ArrayType)
		var lb bytes.Buffer
		if err := printer.Fprint(&lb, token.NewFileSet(), at.Len); err != nil {
			return te.Text
		}
		return fmt.Sprintf("[%s]%s", lb.String(), getTypeName(im, elem(te)))
	case isSlice(te):
		return "[]" + getTypeName(im, elem(te))
	case isMap(te):
		k, v := mapParts(te)
		return fmt.Sprintf("map[%s]%s", getTypeName(im, k), getTypeName(im, v))
	case te.Kind == "ChanType":
		return "chan " + getTypeName(im, elem(te))
	default:
		if sid, ok := te.SymbolID(); ok {
			return qualifiedName(im, sid)
		}
		return te.Text
	}
}

func qualifiedName(im *ImportManager, sid runtime.SymbolID) string {
	if sid.PackagePath == xinspect.BuiltinPackagePath {
		return sid.Name
	}
	return im.Qualify(sid.PackagePath, sid.Name)
}
