package generator

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/printer"
	"go/token"
	"log/slog"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"github.com/podhmo/minigo/examples/convert-define/model"
	xinspect "github.com/podhmo/minigo/inspect"
	"github.com/podhmo/minigo/runtime"
)

const codeTemplate = `
// Code generated by convert. DO NOT EDIT.
{{ .Header -}}
package {{ .PackageName }}

import (
	"context"
	"errors"
	"fmt"
	"github.com/podhmo/minigo/examples/convert-define/model"
	{{- range $path, $alias := .Imports }}
	{{ $alias }} "{{ $path }}"
	{{- end }}
)

{{ range .Pairs -}}
// {{ .ConvName }} converts {{ getQualifiedTypeName $.Im .SrcType }} to {{ getQualifiedTypeName $.Im .DstType }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
{{- if .Warnings }}
//
// Generation warnings — the reported assignments may not compile:
{{- range .Warnings }}
//   - {{ . }}
{{- end }}
{{- end }}
func {{ .ConvName }}(ctx context.Context, ec *model.ErrorCollector, src *{{ getQualifiedTypeName $.Im .SrcType }}) *{{ getQualifiedTypeName $.Im .DstType }} {
	if src == nil {
		return nil
	}
	{{ range .Pair.Variables -}}
	var {{ .Name }} {{ .Type }}
	{{ end -}}
	dst := &{{ getQualifiedTypeName $.Im .DstType }}{}
	{{ range .Fields -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	{{ .Assign }}
	ec.Leave()
	{{ end -}}
	{{ range .Pair.Computed -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	{{ .Prelude }}dst.{{ .DstName }} = {{ .Expr }}
	ec.Leave()
	{{ end -}}
	return dst
}

// {{ .PublicName }} converts {{ getQualifiedTypeName $.Im .SrcType }} to {{ getQualifiedTypeName $.Im .DstType }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
{{- if .Warnings }}
//
// Generation warnings — the reported assignments may not compile:
{{- range .Warnings }}
//   - {{ . }}
{{- end }}
{{- end }}
func {{ .PublicName }}(ctx context.Context, src *{{ getQualifiedTypeName $.Im .SrcType }}) (*{{ getQualifiedTypeName $.Im .DstType }}, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector({{ .Pair.MaxErrors }})
	dst := {{ .ConvName }}(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}
{{ end }}
`

type TemplateData struct {
	PackageName string
	Imports     map[string]string
	Pairs       []TemplatePair
	Im          *ImportManager
	Info        *model.ParsedInfo
	Header      string
}

type TemplatePair struct {
	SrcType        *model.StructInfo
	DstType        *model.StructInfo
	Fields         []FieldMap
	Pair           model.ConversionPair
	UnmappedFields []string
	// Warnings are generate-time diagnostics (e.g. a leaf field pair
	// that falls back to a raw assignment the compiler will reject);
	// they render into the converter's doc comment.
	Warnings []string
	// ConvName/PublicName are the emitted function identifiers; they
	// carry a disambiguating suffix when two pairs would collide.
	ConvName   string
	PublicName string
}

// FieldMap is one src->dst field write inside a generated converter.
// SrcName/DstName are dotted field paths relative to the src/dst
// variables; SrcChain/DstChain hold the resolved FieldInfo per path
// segment (leaf last), so pointer intermediates can be guarded.
type FieldMap struct {
	SrcName   string
	DstName   string
	Converter string // c.Convert's explicit converter func, or ""
	SrcChain  []model.FieldInfo
	DstChain  []model.FieldInfo
	SrcFieldT *xinspect.TypeExpr // leaf source field type
	DstFieldT *xinspect.TypeExpr // leaf destination field type
	// Assign is the emitted assignment block, computed in the emit
	// pass (converter call, rule call, or generated conversion,
	// wrapped in the nil guards/inits nested paths need).
	Assign string
}

// funcNamer maps a "src-decl -> dst-decl" key to the emitted
// converter identifier, so call sites stay consistent when a suffix
// was needed to disambiguate colliding names.
type funcNamer map[string]string

func (fn funcNamer) call(srcElem, dstElem *xinspect.Decl) string {
	if name, ok := fn[model.DeclKey(srcElem)+" -> "+model.DeclKey(dstElem)]; ok {
		return name
	}
	return fmt.Sprintf("convert%sTo%s", srcElem.Name, dstElem.Name)
}

// declNameOf resolves a type expr to the name of the decl it names.
func declNameOf(res xinspect.Resolver, te *xinspect.TypeExpr) string {
	d, err := model.ResolveNamed(res, te)
	if err != nil || d == nil {
		return ""
	}
	return d.Name
}

// isPtr reports whether the declared type is a pointer.
func isPtr(te *xinspect.TypeExpr) bool {
	return te != nil && te.Kind == "StarExpr"
}

// isSlice reports whether the declared type is a slice — `[]T` or
// `...T`. Arrays (`[N]T`, ArrayType with a Len) are handled separately
// since their length is part of the type.
func isSlice(te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	if te.Kind == "Ellipsis" {
		return true
	}
	if at, ok := te.Expr().(*ast.ArrayType); ok {
		return at.Len == nil
	}
	return false
}

// isArray reports whether the declared type is a fixed-length array.
func isArray(te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	at, ok := te.Expr().(*ast.ArrayType)
	return ok && at.Len != nil
}

// isMap reports whether the declared type is a map.
func isMap(te *xinspect.TypeExpr) bool {
	return te != nil && te.Kind == "MapType"
}

// elem returns the element type of a pointer/slice/chan expr, or nil.
func elem(te *xinspect.TypeExpr) *xinspect.TypeExpr {
	if te == nil {
		return nil
	}
	cs := te.Children()
	if len(cs) == 0 {
		return nil
	}
	return cs[len(cs)-1]
}

// mapKeyElem returns the key type of a map expr, or nil.
func mapKeyElem(te *xinspect.TypeExpr) *xinspect.TypeExpr {
	k, _ := mapParts(te)
	return k
}

// mapParts returns the key and element type of a map expr.
func mapParts(te *xinspect.TypeExpr) (k, v *xinspect.TypeExpr) {
	if te == nil {
		return nil, nil
	}
	cs := te.Children()
	if len(cs) != 2 {
		return nil, nil
	}
	return cs[0], cs[1]
}

// isStructType reports whether the type expr resolves to a struct decl.
// Host pseudo-decls (bound stdlib types, e.g. time.Time) and alias decls
// to non-structs all report false — the role IsResolvedByConfig played
// in the previous model.
func isStructType(res xinspect.Resolver, te *xinspect.TypeExpr) bool {
	d, err := model.ResolveNamed(res, te)
	if err != nil {
		return false
	}
	return model.IsStructDecl(d)
}

func Generate(res xinspect.Resolver, info *model.ParsedInfo, header string) ([]byte, error) {
	im := NewImportManager(info.PackagePath)
	ctx := context.Background()

	// Pre-register all necessary imports
	for alias, path := range info.Imports {
		im.Add(path, alias)
	}

	worklist := make([]model.ConversionPair, 0, len(info.ConversionPairs))
	processed := make(map[string]bool)
	allPairs := make([]TemplatePair, 0, len(info.ConversionPairs))

	// Initial population from explicit @derivingconvert annotations
	for _, pair := range info.ConversionPairs {
		key := model.DeclKey(pair.SrcTypeInfo) + " -> " + model.DeclKey(pair.DstTypeInfo)
		if !processed[key] {
			worklist = append(worklist, pair)
			processed[key] = true
		}
	}

	for i := 0; i < len(worklist); i++ {
		pair := worklist[i]

		// Explicit pairs carry their StructInfo already; discovered
		// pairs only know their decls, so materialize the StructInfo
		// here — the same code path as the interpreter's ensureStructInfo.
		srcStruct, err := structInfoFor(info, pair.SrcTypeInfo)
		if err != nil {
			slog.WarnContext(ctx, "source struct for conversion not found in parsed info, skipping", "type", model.DeclKey(pair.SrcTypeInfo), "error", err)
			continue
		}
		dstStruct, err := structInfoFor(info, pair.DstTypeInfo)
		if err != nil {
			slog.WarnContext(ctx, "destination struct for conversion not found in parsed info, skipping", "type", model.DeclKey(pair.DstTypeInfo), "error", err)
			continue
		}

		// Register imports for the current pair's types
		for _, field := range srcStruct.Fields {
			registerImports(im, field.FieldType)
		}
		for _, field := range dstStruct.Fields {
			registerImports(im, field.FieldType)
		}

		fieldMaps, unmappedFields, err := createFieldMaps(ctx, res, info, srcStruct, dstStruct, &pair)
		if err != nil {
			return nil, fmt.Errorf("creating field maps for %s -> %s: %w", srcStruct.Name, dstStruct.Name, err)
		}

		// Discover new pairs from fields — element types plus, for map
		// fields, key types (StructElemOf follows only the value side).
		for _, fm := range fieldMaps {
			typePairs := [][2]*xinspect.TypeExpr{{fm.SrcFieldT, fm.DstFieldT}}
			if sk, dk := mapKeyElem(fm.SrcFieldT), mapKeyElem(fm.DstFieldT); sk != nil && dk != nil {
				typePairs = append(typePairs, [2]*xinspect.TypeExpr{sk, dk})
			}
			for _, tp := range typePairs {
				srcFieldType := model.StructElemOf(res, tp[0])
				dstFieldType := model.StructElemOf(res, tp[1])

				if srcFieldType != nil && dstFieldType != nil {
					key := model.DeclKey(srcFieldType) + " -> " + model.DeclKey(dstFieldType)
					if !processed[key] {
						slog.DebugContext(ctx, "Discovered required conversion", "key", key)
						newPair := model.ConversionPair{
							SrcTypeName: srcFieldType.Name,
							DstTypeName: dstFieldType.Name,
							SrcTypeInfo: srcFieldType,
							DstTypeInfo: dstFieldType,
						}
						worklist = append(worklist, newPair)
						processed[key] = true
					}
				}
			}
		}

		allPairs = append(allPairs, TemplatePair{
			SrcType:        srcStruct,
			DstType:        dstStruct,
			Fields:         fieldMaps,
			Pair:           pair,
			UnmappedFields: unmappedFields,
		})
	}

	// Assign function names after the worklist: pairs that would emit
	// the same converter identifier (e.g. a.User -> b.User and
	// a.User -> c.User) get a deterministic disambiguating suffix.
	funcNames := funcNamer{}
	taken := map[string]bool{}
	for i := range allPairs {
		tp := &allPairs[i]
		base := fmt.Sprintf("%sTo%s", tp.SrcType.Name, tp.DstType.Name)
		name := base
		if taken["convert"+name] {
			name = base + "From" + sanitizeIdent(filepath.Base(tp.SrcType.Type.Package.Path)) + "To" + sanitizeIdent(filepath.Base(tp.DstType.Type.Package.Path))
		}
		for n := 2; taken["convert"+name]; n++ {
			name = fmt.Sprintf("%s%d", base, n)
		}
		taken["convert"+name] = true
		tp.ConvName = "convert" + name
		tp.PublicName = "Convert" + name
		funcNames[model.DeclKey(tp.Pair.SrcTypeInfo)+" -> "+model.DeclKey(tp.Pair.DstTypeInfo)] = tp.ConvName
	}

	// Emit pass: assignment text for every field map is computed here
	// (converter calls, rule calls, generated conversions, and the nil
	// guards/inits nested paths need) so template execution is pure
	// formatting. Leaf-pair mismatches collect as warnings on the pair.
	for i := range allPairs {
		tp := &allPairs[i]
		diag := newGenDiags()
		for j := range tp.Fields {
			tp.Fields[j].Assign = getAssignment(im, res, info, funcNames, tp.Fields[j], "src", "dst", "ec", "ctx", diag)
		}
		for j := range tp.Pair.Computed {
			chain, err := model.ResolveFieldPath(info, res, tp.DstType, tp.Pair.Computed[j].DstName)
			if err != nil {
				return nil, fmt.Errorf("computing %s -> %s field %s: %w", tp.SrcType.Name, tp.DstType.Name, tp.Pair.Computed[j].DstName, err)
			}
			tp.Pair.Computed[j].Prelude = dstInits(im, chain, "dst")
		}
		tp.Warnings = diag.warnings()
		for _, w := range tp.Warnings {
			slog.WarnContext(ctx, w, "converter", tp.ConvName)
		}
	}

	for _, rule := range info.GlobalRules {
		if rule.SrcTypeInfo != nil && rule.SrcTypeInfo.Package != nil {
			im.Qualify(rule.SrcTypeInfo.Package.Path, rule.SrcTypeInfo.Name)
		}
		if rule.DstTypeInfo != nil && rule.DstTypeInfo.Package != nil {
			im.Qualify(rule.DstTypeInfo.Package.Path, rule.DstTypeInfo.Name)
		}
	}

	templateData := TemplateData{
		PackageName: info.PackageName,
		Imports:     im.Imports(),
		Pairs:       allPairs,
		Im:          im,
		Info:        info,
		Header:      header,
	}

	funcMap := template.FuncMap{
		"getQualifiedTypeName": func(im *ImportManager, structInfo *model.StructInfo) string {
			if structInfo == nil || structInfo.Type == nil || structInfo.Type.Package == nil {
				return "invalid"
			}
			// When generating code for a specific package, types within that package don't need qualification.
			if structInfo.Type.Package.Path == info.PackagePath && info.PackagePath != "" {
				return structInfo.Name
			}
			return im.Qualify(structInfo.Type.Package.Path, structInfo.Name)
		},
	}

	tmpl, err := template.New("converter").Funcs(funcMap).Parse(codeTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	return buf.Bytes(), nil
}

// structInfoFor returns the StructInfo for a conversion decl,
// materializing it from the decl when the interpreter's pass did not
// (the common case for types discovered through field traversal).
func structInfoFor(info *model.ParsedInfo, d *xinspect.Decl) (*model.StructInfo, error) {
	key := model.DeclKey(d)
	if si, ok := info.Structs[key]; ok {
		return si, nil
	}
	si, err := model.StructInfoFromDecl(d)
	if err != nil {
		return nil, err
	}
	info.Structs[key] = si
	return si, nil
}

// sanitizeIdent renders a package path as an identifier-safe fragment
// for converter-name disambiguation ("a/b/c" -> "abc").
func sanitizeIdent(path string) string {
	var b strings.Builder
	for _, r := range path {
		if r == '_' || r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func createFieldMaps(ctx context.Context, res xinspect.Resolver, info *model.ParsedInfo, src, dst *model.StructInfo, pair *model.ConversionPair) ([]FieldMap, []string, error) {
	var maps []FieldMap
	dstFieldsByNormalizedJSONTag := make(map[string]model.FieldInfo)
	dstFieldsByNormalizedName := make(map[string]model.FieldInfo)
	unmappedDstFields := make(map[string]bool)
	// Top-level src fields claimed by an explicit c.Map/c.Convert —
	// name/json matching must not double-assign them.
	consumedSrcFields := make(map[string]bool)

	slog.DebugContext(ctx, "Destination struct", "name", dst.Name)
	for _, f := range dst.Fields {
		if f.JSONTag != "" && f.JSONTag != "-" {
			normalized := normalizeFieldName(f.JSONTag)
			dstFieldsByNormalizedJSONTag[normalized] = f
			slog.DebugContext(ctx, "dst field", "name", f.Name, "json", f.JSONTag, "normalized_json", normalized)
		}
		normalized := normalizeFieldName(f.Name)
		dstFieldsByNormalizedName[normalized] = f
		slog.DebugContext(ctx, "dst field", "name", f.Name, "normalized_name", normalized)
		unmappedDstFields[f.Name] = true
	}

	// Explicit c.Map/c.Convert entries. Both sides were already
	// validated by the walker; here they resolve again to leaf types.
	// A nested src path leaves its top field available for matching;
	// a plain field name claims it.
	var explicit []FieldMap
	if pair.Mapping != nil {
		for _, m := range pair.Mapping.Maps {
			srcChain, err := model.ResolveFieldPath(info, res, src, m.SrcName)
			if err != nil {
				return nil, nil, fmt.Errorf("mapping %s -> %s: %w", m.SrcName, m.DstName, err)
			}
			dstChain, err := model.ResolveFieldPath(info, res, dst, m.DstName)
			if err != nil {
				return nil, nil, fmt.Errorf("mapping %s -> %s: %w", m.SrcName, m.DstName, err)
			}
			if !strings.Contains(m.SrcName, ".") {
				consumedSrcFields[m.SrcName] = true
			}
			delete(unmappedDstFields, firstSeg(m.DstName))
			explicit = append(explicit, FieldMap{
				SrcName:   m.SrcName,
				DstName:   m.DstName,
				Converter: m.Converter,
				SrcChain:  srcChain,
				DstChain:  dstChain,
				SrcFieldT: srcChain[len(srcChain)-1].FieldType,
				DstFieldT: dstChain[len(dstChain)-1].FieldType,
			})
		}
	}

	// Remove computed fields from the unmapped list (a nested compute
	// destination counts its top-level field as populated).
	for _, computed := range pair.Computed {
		delete(unmappedDstFields, firstSeg(computed.DstName))
	}

	slog.DebugContext(ctx, "Source struct", "name", src.Name)
	for _, srcField := range src.Fields {
		if consumedSrcFields[srcField.Name] {
			slog.DebugContext(ctx, "src field claimed by explicit mapping", "name", srcField.Name)
			continue
		}

		var dstField model.FieldInfo
		var ok bool
		var reason string

		// Priority 1: Normalized `json` tag
		if srcField.JSONTag != "" && srcField.JSONTag != "-" {
			normalizedJSONTag := normalizeFieldName(srcField.JSONTag)
			dstField, ok = dstFieldsByNormalizedJSONTag[normalizedJSONTag]
			reason = fmt.Sprintf("normalized `json` tag (%s -> %s)", srcField.JSONTag, normalizedJSONTag)
		}

		// Priority 2: Normalized field name
		if !ok {
			normalizedSrcName := normalizeFieldName(srcField.Name)
			dstField, ok = dstFieldsByNormalizedName[normalizedSrcName]
			reason = fmt.Sprintf("normalized name (%s -> %s)", srcField.Name, normalizedSrcName)
		}

		if !ok {
			slog.DebugContext(ctx, "src field no match found", "name", srcField.Name)
			continue
		}

		slog.DebugContext(ctx, "src field matched", "src", srcField.Name, "dst", dstField.Name, "reason", reason)
		delete(unmappedDstFields, dstField.Name)
		maps = append(maps, FieldMap{
			SrcName:   srcField.Name,
			DstName:   dstField.Name,
			SrcChain:  []model.FieldInfo{srcField},
			DstChain:  []model.FieldInfo{dstField},
			SrcFieldT: srcField.FieldType,
			DstFieldT: dstField.FieldType,
		})
	}

	// Explicit maps emit last, so a leaf-path mapping overrides the
	// whole-struct auto assignment of a shared ancestor (e.g.
	// c.Map(dst.Inner.ID, src.ID) after dst.Inner = convert(src.Inner)).
	maps = append(maps, explicit...)

	// Collect unmapped fields
	var unmapped []string
	for fieldName := range unmappedDstFields {
		unmapped = append(unmapped, fieldName)
	}
	// sort for deterministic output
	slices.Sort(unmapped)

	return maps, unmapped, nil
}

// firstSeg returns the first segment of a field path ("Inner.ID" -> "Inner").
func firstSeg(path string) string {
	if i := strings.IndexByte(path, '.'); i >= 0 {
		return path[:i]
	}
	return path
}

func normalizeFieldName(name string) string {
	return strings.ToLower(strings.ReplaceAll(name, "_", ""))
}

func qualifyFunc(im *ImportManager, info *model.ParsedInfo, funcName string) string {
	parts := strings.Split(funcName, ".")
	if len(parts) != 2 {
		return funcName // Not a qualified function name, assume it's in the current package
	}
	alias, name := parts[0], parts[1]
	path, ok := info.Imports[alias]
	if !ok {
		slog.Warn("could not find import path for alias in function", "alias", alias, "funcName", funcName)
		return funcName
	}
	finalAlias := im.Add(path, alias)
	return finalAlias + "." + name
}

// registerImports qualifies every named type reachable through the
// TypeExpr — pointers, slices, maps, func types, and generic
// instantiation bases (pkg.List in pkg.List[T]), which Children() does
// not yield and so are reached via Sub.
func registerImports(im *ImportManager, te *xinspect.TypeExpr) {
	if te == nil {
		return
	}
	if sid, ok := te.SymbolID(); ok {
		if sid.PackagePath != xinspect.BuiltinPackagePath {
			im.Qualify(sid.PackagePath, sid.Name)
		}
		return
	}
	switch e := te.Expr().(type) {
	case *ast.IndexExpr:
		registerImports(im, te.Sub(e.X))
	case *ast.IndexListExpr:
		registerImports(im, te.Sub(e.X))
	}
	for _, c := range te.Children() {
		registerImports(im, c)
	}
}

// -----------------------------------------------------------------------------
// Assignment Logic
// -----------------------------------------------------------------------------

type ruleMatchResult struct {
	Rule           *model.TypeRule
	IsPointerMatch bool
}

func findMatchingRule(info *model.ParsedInfo, srcT, dstT *xinspect.TypeExpr) *ruleMatchResult {
	if srcT == nil || dstT == nil {
		return nil
	}

	srcFieldTypeName := srcT.CanonicalName()
	dstFieldTypeName := dstT.CanonicalName()

	for i := range info.GlobalRules {
		rule := &info.GlobalRules[i]
		if rule.UsingFunc == "" {
			continue
		}

		if rule.SrcTypeName == srcFieldTypeName && rule.DstTypeName == dstFieldTypeName {
			// Determine if it's a pointer match based on the source field type.
			// This is simpler than trying to infer from the rule's TypeInfo.
			return &ruleMatchResult{Rule: rule, IsPointerMatch: isPtr(srcT)}
		}
	}

	return nil
}

func getMapKeyAssignment(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, srcVar, dstVar string, srcT, dstT *xinspect.TypeExpr, ecVar, ctxVar string, diag *genDiags) string {
	// Global conversion rule
	if match := findMatchingRule(info, srcT, dstT); match != nil {
		funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
		if dstVar != "" {
			return fmt.Sprintf("%s = %s(%s, %s, %s)", dstVar, funcName, ctxVar, ecVar, srcVar)
		}
		return fmt.Sprintf("%s(%s, %s, %s)", funcName, ctxVar, ecVar, srcVar)
	}
	return generateConversion(im, res, info, fn, srcVar, dstVar, srcT, dstT, 0, ecVar, ctxVar, diag)
}

// getAssignment renders one field write. For nested paths the body is
// preceded by dst-side nil inits (pointer intermediates must exist
// before their leaf is written) and wrapped in src-side nil guards (a
// nil pointer intermediate means "no value to copy").
func getAssignment(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, field FieldMap, srcVar, dstVar, ecVar, ctxVar string, diag *genDiags) string {
	src := fmt.Sprintf("%s.%s", srcVar, field.SrcName)
	dst := fmt.Sprintf("%s.%s", dstVar, field.DstName)

	var body string
	switch {
	// Priority 1: field-level converter (c.Convert)
	case field.Converter != "":
		funcName := qualifyFunc(im, info, field.Converter)
		body = fmt.Sprintf("%s = %s(%s, %s, %s)", dst, funcName, ctxVar, ecVar, src)
	default:
		if match := findMatchingRule(info, field.SrcFieldT, field.DstFieldT); match != nil {
			// Priority 2: global conversion rule — the user-provided
			// function is expected to have the correct signature
			// (e.g., handle pointers correctly). We just call it.
			funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
			body = fmt.Sprintf("%s = %s(%s, %s, %s)", dst, funcName, ctxVar, ecVar, src)
		} else {
			// Priority 3: default conversion logic — warnings are
			// labelled with the destination path of this field.
			body = generateConversion(im, res, info, fn, src, dst, field.SrcFieldT, field.DstFieldT, 0, ecVar, ctxVar, diag.at(dst))
		}
	}

	return srcGuardWrap(dstInits(im, field.DstChain, dstVar)+body, field.SrcChain, srcVar)
}

// chainPath renders the first n segments of a resolved field chain
// joined by "." — the access path of the n-th field.
func chainPath(chain []model.FieldInfo, n int) string {
	parts := make([]string, n)
	for i := 0; i < n; i++ {
		parts[i] = chain[i].Name
	}
	return strings.Join(parts, ".")
}

// dstInits emits `if p == nil { p = &T{} }` for every pointer
// intermediate in a destination path, so writes into `dst.In.X`
// cannot panic. Depth-1 chains emit nothing.
func dstInits(im *ImportManager, chain []model.FieldInfo, dstVar string) string {
	var b strings.Builder
	for i := 0; i+1 < len(chain); i++ {
		ft := chain[i].FieldType
		if !isPtr(ft) {
			continue
		}
		p := dstVar + "." + chainPath(chain, i+1)
		fmt.Fprintf(&b, "if %s == nil {\n\t%s = &%s{}\n}\n", p, p, getTypeName(im, elem(ft)))
	}
	return b.String()
}

// srcGuardWrap nests body inside `if p != nil {}` for every pointer
// intermediate in a source path — outermost guard outermost. Depth-1
// chains return body unchanged.
func srcGuardWrap(body string, chain []model.FieldInfo, srcVar string) string {
	for i := len(chain) - 2; i >= 0; i-- {
		if !isPtr(chain[i].FieldType) {
			continue
		}
		p := srcVar + "." + chainPath(chain, i+1)
		body = fmt.Sprintf("if %s != nil {\n%s\n}", p, indentLines(body))
	}
	return body
}

// indentLines prefixes each non-empty line with a tab — emitted code
// is normalized by goimports afterwards, this only keeps the raw text
// readable.
func indentLines(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = "\t" + l
		}
	}
	return strings.Join(lines, "\n")
}

func generateConversion(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, src, dst string, srcT, dstT *xinspect.TypeExpr, depth int, ecVar, ctxVar string, diag *genDiags) string {
	// Global conversion rule
	if match := findMatchingRule(info, srcT, dstT); match != nil {
		funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
		result := fmt.Sprintf("%s(%s, %s, %s)", funcName, ctxVar, ecVar, src)
		if dst != "" {
			return fmt.Sprintf("%s = %s", dst, result)
		}
		return result
	}

	if srcT == nil || dstT == nil {
		return fmt.Sprintf("// srcT or dstT is nil for %s -> %s", src, dst)
	}

	// Identical value types assign directly — same-name structs, same
	// scalars, etc. Pointers, slices and maps are excluded: they fall
	// through to the shape branches below, which allocate fresh copies
	// instead of aliasing the source's memory.
	if srcT.SameType(dstT, res) && !isPtr(srcT) && !isSlice(srcT) && !isMap(srcT) {
		if dst != "" {
			return fmt.Sprintf("%s = %s", dst, src)
		}
		return src
	}

	// Pointer to Pointer
	if isPtr(srcT) && isPtr(dstT) {
		srcElem, dstElem := elem(srcT), elem(dstT)
		if srcElem == nil || dstElem == nil {
			// Fallback for unresolved types or built-in pointers like *int
			if dst != "" {
				return fmt.Sprintf("%s = %s", dst, src)
			}
			return src
		}

		// If the elements are structs that have a dedicated converter, use
		// it directly — but only at exactly one level of indirection:
		// `**T` is not a `*T` argument.
		srcElemDecl, dstElemDecl := namedDeclOf(res, srcElem), namedDeclOf(res, dstElem)
		if !isPtr(srcElem) && !isPtr(dstElem) && model.IsStructDecl(srcElemDecl) && model.IsStructDecl(dstElemDecl) {
			call := fmt.Sprintf("%s(%s, %s, %s)", fn.call(srcElemDecl, dstElemDecl), ctxVar, ecVar, src)
			if dst != "" {
				return fmt.Sprintf("%s = %s", dst, call)
			}
			return call
		}

		var b strings.Builder
		if dst != "" {
			// If dst is specified, we generate a block of statements.
			b.WriteString(fmt.Sprintf("if %s != nil {\n", src))
			b.WriteString(fmt.Sprintf("\ttmp := %s\n", generateConversion(im, res, info, fn, "(*"+src+")", "", srcElem, dstElem, depth+1, ecVar, ctxVar, diag)))
			b.WriteString(fmt.Sprintf("\t%s = &tmp\n", dst))
			b.WriteString("} else {\n")
			b.WriteString(fmt.Sprintf("\t%s = nil\n", dst))
			b.WriteString("}")
		} else {
			// If dst is empty, we must generate an expression, which we do with an anonymous func.
			b.WriteString(fmt.Sprintf("func() %s {\n", getTypeName(im, dstT)))
			b.WriteString(fmt.Sprintf("\tif %s == nil { return nil }\n", src))
			b.WriteString(fmt.Sprintf("\ttmp := %s\n", generateConversion(im, res, info, fn, "(*"+src+")", "", srcElem, dstElem, depth+1, ecVar, ctxVar, diag)))
			b.WriteString("\treturn &tmp\n")
			b.WriteString("}()")
		}
		return b.String()
	}
	// Pointer to Value
	if isPtr(srcT) && !isPtr(dstT) {
		srcElem := elem(srcT)
		if srcElem == nil {
			return fmt.Sprintf("// Cannot convert pointer to value, element type is nil")
		}
		inner := generateConversion(im, res, info, fn, "(*"+src+")", "", srcElem, dstT, depth+1, ecVar, ctxVar, diag)
		if dst != "" {
			return fmt.Sprintf("if %s != nil {\n\t%s = %s\n}", src, dst, inner)
		}
		return fmt.Sprintf("func() %s {\n\tif %s == nil { var z %s; return z }\n\treturn %s\n}()", getTypeName(im, dstT), src, getTypeName(im, dstT), inner)
	}
	// Value to Pointer
	if !isPtr(srcT) && isPtr(dstT) {
		dstElem := elem(dstT)
		if dstElem == nil {
			return fmt.Sprintf("// Cannot convert value to pointer, element type is nil")
		}
		inner := generateConversion(im, res, info, fn, src, "", srcT, dstElem, depth+1, ecVar, ctxVar, diag)
		if dst != "" {
			return fmt.Sprintf("{\n\ttmp := %s\n\t%s = &tmp\n}", inner, dst)
		}
		return fmt.Sprintf("func() %s {\n\ttmp := %s\n\treturn &tmp\n}()", getTypeName(im, dstT), inner)
	}

	// Slices
	if isSlice(srcT) && isSlice(dstT) {
		return generateSliceConversion(im, res, info, fn, src, dst, srcT, dstT, depth, ecVar, ctxVar, diag)
	}

	// Arrays: fixed-length; element conversion proceeds one index at a
	// time (same-type arrays already assigned above).
	if isArray(srcT) && isArray(dstT) {
		return generateArrayConversion(im, res, info, fn, src, dst, srcT, dstT, depth, ecVar, ctxVar, diag)
	}

	// Maps
	if isMap(srcT) && isMap(dstT) {
		return generateMapConversion(im, res, info, fn, src, dst, srcT, dstT, depth, ecVar, ctxVar, diag)
	}

	// Structs
	srcDecl, dstDecl := namedDeclOf(res, srcT), namedDeclOf(res, dstT)
	if model.IsStructDecl(srcDecl) && model.IsStructDecl(dstDecl) {
		srcPtr := src
		if !isPtr(srcT) {
			srcPtr = "&" + src
		}
		conversion := fmt.Sprintf("*%s(%s, %s, %s)", fn.call(srcDecl, dstDecl), ctxVar, ecVar, srcPtr)
		if dst != "" {
			return fmt.Sprintf("%s = %s", dst, conversion)
		}
		return conversion
	}

	// Basic assignment — with a type conversion when the canonical names
	// differ but the shape is castable (named leaf types, numeric pairs).
	// When neither applies the raw assignment is kept (it is what the
	// compiler sees), but the mismatch is reported as a generation
	// warning instead of failing silently at compile time.
	if dst != "" {
		if cast, ok := leafCast(im, res, srcT, dstT, src); ok {
			return fmt.Sprintf("%s = %s", dst, cast)
		}
		diag.warn(leafMismatch(im, res, srcT, dstT))
		return fmt.Sprintf("%s = %s", dst, src)
	}
	if cast, ok := leafCast(im, res, srcT, dstT, src); ok {
		return cast
	}
	diag.warn(leafMismatch(im, res, srcT, dstT))
	return src
}

// genDiags accumulates generate-time warnings for one converter —
// leaf pairs that fall back to a raw assignment between incompatible
// types. The generated code still emits the assignment (it is the
// honest output); the warning surfaces in the doc comment and via
// slog so the failure is visible before compile time.
type genDiags struct {
	site  string // label prepended to each warning (the dst field path)
	items *[]string
	seen  map[string]bool
}

func newGenDiags() *genDiags {
	return &genDiags{items: new([]string), seen: map[string]bool{}}
}

// at returns a view that labels every warning with the given site.
func (d *genDiags) at(site string) *genDiags {
	return &genDiags{site: site, items: d.items, seen: d.seen}
}

// warn records a warning, prefixed by the site label and deduplicated.
func (d *genDiags) warn(msg string) {
	if msg == "" {
		return
	}
	if d.site != "" {
		msg = d.site + ": " + msg
	}
	if d.seen[msg] {
		return
	}
	d.seen[msg] = true
	*d.items = append(*d.items, msg)
}

func (d *genDiags) warnings() []string {
	return *d.items
}

// leafMismatch describes a leaf src/dst pair that no rule, cast, or
// shape branch covers — the raw assignment that follows will not
// compile. Returns "" when the pair is safely assignable after all
// (dst accepts any value, or a named src may satisfy a dst interface).
func leafMismatch(im *ImportManager, res xinspect.Resolver, srcT, dstT *xinspect.TypeExpr) string {
	if isEmptyIface(res, dstT) {
		return ""
	}
	// A non-empty interface dst is satisfied whenever the src is a
	// named type that could carry the methods — without go/types that
	// cannot be verified, so stay quiet rather than cry wolf.
	if isIfaceDecl(namedDeclOf(res, dstT)) {
		if sid, ok := srcT.Unref().SymbolID(); ok && sid.PackagePath != xinspect.BuiltinPackagePath {
			return ""
		}
	}
	return fmt.Sprintf("no conversion covers %s -> %s", getTypeName(im, srcT), getTypeName(im, dstT))
}

// isIfaceDecl reports whether the declaration is a named interface type.
func isIfaceDecl(d *xinspect.Decl) bool {
	if d == nil || d.Kind != "type" {
		return false
	}
	def, err := xinspect.DefOf(d)
	return err == nil && def.Kind == "InterfaceType"
}

// isEmptyIface reports whether the type accepts every value: `any`, a
// literal `interface{}`, or a named type whose decl is an empty
// interface.
func isEmptyIface(res xinspect.Resolver, te *xinspect.TypeExpr) bool {
	if te == nil {
		return false
	}
	if sid, ok := te.SymbolID(); ok && sid.PackagePath == xinspect.BuiltinPackagePath && sid.Name == "any" {
		return true
	}
	if it, ok := te.Expr().(*ast.InterfaceType); ok && len(it.Methods.List) == 0 {
		return true
	}
	if d := namedDeclOf(res, te); d != nil {
		if def, err := xinspect.DefOf(d); err == nil {
			if it, ok := def.Expr().(*ast.InterfaceType); ok && len(it.Methods.List) == 0 {
				return true
			}
		}
	}
	return false
}

// namedDeclOf resolves a type expr to its declaration, or nil for
// builtins and composite shapes.
func namedDeclOf(res xinspect.Resolver, te *xinspect.TypeExpr) *xinspect.Decl {
	d, err := model.ResolveNamed(res, te)
	if err != nil {
		return nil
	}
	return d
}

// numericBuiltins is the set of predeclared numeric types — casts
// between them are always legal Go.
var numericBuiltins = map[string]bool{
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
	"uintptr": true, "byte": true, "rune": true,
	"float32": true, "float64": true, "complex64": true, "complex128": true,
}

// leafCast reports the `dstT(src)` cast to emit when src and dst are
// leaf types with different canonical names: either side being a named
// (non-builtin) type that is not itself a struct/interface, or both
// being numeric builtins, makes a plain conversion legal; string <->
// []byte/[]rune converts natively; anything else is left to a raw
// assignment that the compiler will flag if it is truly wrong.
func leafCast(im *ImportManager, res xinspect.Resolver, srcT, dstT *xinspect.TypeExpr, src string) (string, bool) {
	// string <-> []byte / []rune — the only builtin leaf/composite
	// pairs Go can convert directly.
	if isStringLeaf(dstT) && isByteOrRuneSlice(srcT) {
		return fmt.Sprintf("string(%s)", src), true
	}
	if isStringLeaf(srcT) && isByteOrRuneSlice(dstT) {
		return fmt.Sprintf("%s(%s)", getTypeName(im, dstT), src), true
	}

	srcCanon, dstCanon := srcT.CanonicalName(), dstT.CanonicalName()
	if srcCanon == "" || dstCanon == "" || srcCanon == dstCanon {
		return "", false
	}
	// A named type is castable to an unrelated leaf only when its decl
	// is not a struct or interface — `string(time.Time)` does not
	// compile but `string(MyInt)` does. Unresolvable decls keep the
	// previous optimistic behaviour.
	isCastableNamed := func(te *xinspect.TypeExpr) bool {
		sid, ok := te.Unref().SymbolID()
		if !ok || sid.PackagePath == xinspect.BuiltinPackagePath {
			return false
		}
		if d, err := model.ResolveNamed(res, te); err == nil && d != nil {
			if model.IsStructDecl(d) || isIfaceDecl(d) {
				return false
			}
		}
		return true
	}
	if isCastableNamed(dstT) || isCastableNamed(srcT) || (numericBuiltins[srcCanon] && numericBuiltins[dstCanon]) {
		return fmt.Sprintf("%s(%s)", getTypeName(im, dstT), src), true
	}
	return "", false
}

// isStringLeaf reports whether the type is the builtin string type.
func isStringLeaf(te *xinspect.TypeExpr) bool {
	return te != nil && te.CanonicalName() == "string"
}

// isByteOrRuneSlice reports whether the type is []byte/[]uint8 or
// []rune/[]int32 — the slice shapes convertible to and from string.
func isByteOrRuneSlice(te *xinspect.TypeExpr) bool {
	if !isSlice(te) {
		return false
	}
	e := elem(te)
	if e == nil {
		return false
	}
	switch e.CanonicalName() {
	case "byte", "uint8", "rune", "int32":
		return true
	}
	return false
}

func generateArrayConversion(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, src, dst string, srcT, dstT *xinspect.TypeExpr, depth int, ecVar, ctxVar string, diag *genDiags) string {
	srcElem, dstElem := elem(srcT), elem(dstT)
	if srcElem == nil || dstElem == nil {
		return ""
	}
	dstType := getTypeName(im, dstT)
	conv := generateConversion(im, res, info, fn, "item", "", srcElem, dstElem, depth+2, ecVar, ctxVar, diag)

	var b strings.Builder
	if dst != "" {
		b.WriteString(fmt.Sprintf("{\n\tfor i, item := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\t%s[i] = %s\n", dst, conv))
		b.WriteString("\t\t" + ecVar + ".Leave()\n\t}\n}")
	} else {
		b.WriteString(fmt.Sprintf("func() %s {\n\tvar arr %s\n\tfor i, item := range %s {\n", dstType, dstType, src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\tarr[i] = %s\n", conv))
		b.WriteString("\t\t" + ecVar + ".Leave()\n\t}\n\treturn arr\n}()")
	}
	return b.String()
}

func generateSliceConversion(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, src, dst string, srcT, dstT *xinspect.TypeExpr, depth int, ecVar, ctxVar string, diag *genDiags) string {
	srcElem, dstElem := elem(srcT), elem(dstT)
	if srcElem == nil || dstElem == nil {
		return ""
	}

	var b strings.Builder
	if dst != "" {
		b.WriteString("{\n")
		b.WriteString(fmt.Sprintf("\tconvertedSlice := make([]%s, len(%s))\n", getTypeName(im, dstElem), src))
		b.WriteString(fmt.Sprintf("\tfor i, item := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedSlice[i] = %s\n", generateConversion(im, res, info, fn, "item", "", srcElem, dstElem, depth+2, ecVar, ctxVar, diag)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s = convertedSlice\n", dst))
		b.WriteString("}")
	} else {
		b.WriteString(fmt.Sprintf("func() []%s {\n", getTypeName(im, dstElem)))
		b.WriteString(fmt.Sprintf("\tconvertedSlice := make([]%s, len(%s))\n", getTypeName(im, dstElem), src))
		b.WriteString(fmt.Sprintf("\tfor i, item := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedSlice[i] = %s\n", generateConversion(im, res, info, fn, "item", "", srcElem, dstElem, depth+2, ecVar, ctxVar, diag)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn convertedSlice\n")
		b.WriteString("}()")
	}
	return b.String()
}

func generateMapConversion(im *ImportManager, res xinspect.Resolver, info *model.ParsedInfo, fn funcNamer, src, dst string, srcT, dstT *xinspect.TypeExpr, depth int, ecVar, ctxVar string, diag *genDiags) string {
	srcKT, srcVT := mapParts(srcT)
	dstKT, dstVT := mapParts(dstT)
	if srcKT == nil || srcVT == nil || dstKT == nil || dstVT == nil {
		return ""
	}

	keyExpr := func() string {
		if srcKT.SameType(dstKT, res) {
			return "key"
		}
		return getMapKeyAssignment(im, res, info, fn, "key", "", srcKT, dstKT, ecVar, ctxVar, diag)
	}

	var b strings.Builder
	if dst != "" {
		b.WriteString("{\n")
		b.WriteString(fmt.Sprintf("\tconvertedMap := make(map[%s]%s, len(%s))\n", getTypeName(im, dstKT), getTypeName(im, dstVT), src))
		b.WriteString(fmt.Sprintf("\tfor key, value := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%v]\", key))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedMap[%s] = %s\n",
			keyExpr(),
			generateConversion(im, res, info, fn, "value", "", srcVT, dstVT, depth+2, ecVar, ctxVar, diag)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s = convertedMap\n", dst))
		b.WriteString("}")
	} else {
		b.WriteString(fmt.Sprintf("func() map[%s]%s {\n", getTypeName(im, dstKT), getTypeName(im, dstVT)))
		b.WriteString(fmt.Sprintf("\tconvertedMap := make(map[%s]%s, len(%s))\n", getTypeName(im, dstKT), getTypeName(im, dstVT), src))
		b.WriteString(fmt.Sprintf("\tfor key, value := range %s {\n", src))

		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%v]\", key))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedMap[%s] = %s\n",
			keyExpr(),
			generateConversion(im, res, info, fn, "value", "", srcVT, dstVT, depth+2, ecVar, ctxVar, diag)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn convertedMap\n")
		b.WriteString("}()")
	}
	return b.String()
}

// getTypeName renders a TypeExpr in the generated file's terms —
// declared identifiers become im.Qualify'd names; composite shapes that
// carry no resolvable identity (anonymous struct/func types) keep the
// written spelling.
func getTypeName(im *ImportManager, te *xinspect.TypeExpr) string {
	if te == nil {
		return "interface{}" // Should not happen in valid code
	}

	switch e := te.Expr().(type) {
	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", getTypeName(im, te.Sub(e.X)), getTypeName(im, te.Sub(e.Index)))
	case *ast.IndexListExpr:
		var args []string
		for _, ix := range e.Indices {
			args = append(args, getTypeName(im, te.Sub(ix)))
		}
		return fmt.Sprintf("%s[%s]", getTypeName(im, te.Sub(e.X)), strings.Join(args, ","))
	}

	switch {
	case isPtr(te):
		if e := elem(te); e != nil {
			return "*" + getTypeName(im, e)
		}
		return te.Text // te.Text already carries the "*"
	case isArray(te):
		at := te.Expr().(*ast.ArrayType)
		var lb bytes.Buffer
		if err := printer.Fprint(&lb, token.NewFileSet(), at.Len); err != nil {
			return te.Text
		}
		return fmt.Sprintf("[%s]%s", lb.String(), getTypeName(im, elem(te)))
	case isSlice(te):
		return "[]" + getTypeName(im, elem(te))
	case isMap(te):
		k, v := mapParts(te)
		return fmt.Sprintf("map[%s]%s", getTypeName(im, k), getTypeName(im, v))
	case te.Kind == "ChanType":
		return "chan " + getTypeName(im, elem(te))
	default:
		if sid, ok := te.SymbolID(); ok {
			return qualifiedName(im, sid)
		}
		return te.Text
	}
}

func qualifiedName(im *ImportManager, sid runtime.SymbolID) string {
	if sid.PackagePath == xinspect.BuiltinPackagePath {
		return sid.Name
	}
	return im.Qualify(sid.PackagePath, sid.Name)
}
