package generator

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"slices"
	"strings"
	"text/template"

	"github.com/podhmo/minigo/examples/convert-define/model"
	goscan "github.com/podhmo/minigo/examples/convert-define/pkg/goscan"
	"github.com/podhmo/minigo/examples/convert-define/pkg/scanner"
)

const codeTemplate = `
// Code generated by convert. DO NOT EDIT.
{{ .Header -}}
package {{ .PackageName }}

import (
	"context"
	"errors"
	"fmt"
	"github.com/podhmo/minigo/examples/convert-define/model"
	{{- range $path, $alias := .Imports }}
	{{ $alias }} "{{ $path }}"
	{{- end }}
)

{{ range .Pairs -}}
// convert{{ .SrcType.Name }}To{{ .DstType.Name }} converts {{ getQualifiedTypeName $.Im .SrcType }} to {{ getQualifiedTypeName $.Im .DstType }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
func convert{{ .SrcType.Name }}To{{ .DstType.Name }}(ctx context.Context, ec *model.ErrorCollector, src *{{ getQualifiedTypeName $.Im .SrcType }}) *{{ getQualifiedTypeName $.Im .DstType }} {
	if src == nil {
		return nil
	}
	{{ range .Pair.Variables -}}
	var {{ .Name }} {{ .Type }}
	{{ end -}}
	dst := &{{ getQualifiedTypeName $.Im .DstType }}{}
	{{ range .Fields -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	{{ $assignment := getAssignment $.Im $.Info . "src" "dst" "ec" "ctx" -}}
	{{ $validator := getValidator $.Im $.Info . "dst" "ec" "ctx" -}}
	{{ $assignment }}
	{{ if $validator -}}
	{{ $validator }}
	{{- end }}
	ec.Leave()
	{{ end -}}
	{{ range .Pair.Computed -}}
	if ec.MaxErrorsReached() { return dst }
	ec.Enter("{{ .DstName }}")
	dst.{{ .DstName }} = {{ .Expr }}
	ec.Leave()
	{{ end -}}
	return dst
}

// Convert{{ .SrcType.Name }}To{{ .DstType.Name }} converts {{ getQualifiedTypeName $.Im .SrcType }} to {{ getQualifiedTypeName $.Im .DstType }}.
{{- if .UnmappedFields }}
//
// Fields that are not populated by this converter:
{{- range .UnmappedFields }}
//   - {{ . }}
{{- end }}
{{- end }}
func Convert{{ .SrcType.Name }}To{{ .DstType.Name }}(ctx context.Context, src *{{ getQualifiedTypeName $.Im .SrcType }}) (*{{ getQualifiedTypeName $.Im .DstType }}, error) {
	if src == nil {
		return nil, nil
	}
	ec := model.NewErrorCollector({{ .Pair.MaxErrors }})
	dst := convert{{ .SrcType.Name }}To{{ .DstType.Name }}(ctx, ec, src)
	if ec.HasErrors() {
		return dst, errors.Join(ec.Errors()...)
	}
	return dst, nil
}
{{ end }}
`

type TemplateData struct {
	PackageName string
	Imports     map[string]string
	Pairs       []TemplatePair
	Im          *goscan.ImportManager
	Info        *model.ParsedInfo
	Header      string
}

type TemplatePair struct {
	SrcType        *model.StructInfo
	DstType        *model.StructInfo
	Fields         []FieldMap
	Pair           model.ConversionPair
	UnmappedFields []string
}

type FieldMap struct {
	SrcName   string
	DstName   string
	Tag       model.ConvertTag
	SrcFieldT *scanner.FieldType
	DstFieldT *scanner.FieldType
}

func Generate(s *goscan.Scanner, info *model.ParsedInfo, header string) ([]byte, error) {
	im := goscan.NewImportManager(&scanner.PackageInfo{ImportPath: info.PackagePath, Name: info.PackageName})
	ctx := context.Background()

	// Pre-register all necessary imports
	for alias, path := range info.Imports {
		im.Add(path, alias)
	}

	worklist := make([]model.ConversionPair, 0, len(info.ConversionPairs))
	processed := make(map[string]bool)
	allPairs := make([]TemplatePair, 0, len(info.ConversionPairs))

	// Initial population from explicit @derivingconvert annotations
	for _, pair := range info.ConversionPairs {
		key := fmt.Sprintf("%s.%s -> %s.%s", pair.SrcTypeInfo.PkgPath, pair.SrcTypeName, pair.DstTypeInfo.PkgPath, pair.DstTypeName)
		if !processed[key] {
			worklist = append(worklist, pair)
			processed[key] = true
		}
	}

	for i := 0; i < len(worklist); i++ {
		pair := worklist[i]

		srcStruct, ok := info.Structs[pair.SrcTypeName]
		if !ok {
			// This can happen if a struct is referenced but not defined in the scanned packages.
			slog.WarnContext(ctx, "source struct for conversion not found in parsed info, skipping", "type", pair.SrcTypeName)
			continue
		}
		dstStruct, ok := info.Structs[pair.DstTypeName]
		if !ok {
			slog.WarnContext(ctx, "destination struct for conversion not found in parsed info, skipping", "type", pair.DstTypeName)
			continue
		}

		// Register imports for the current pair's types
		for _, field := range srcStruct.Fields {
			registerImports(im, field.FieldType)
		}
		for _, field := range dstStruct.Fields {
			registerImports(im, field.FieldType)
		}

		fieldMaps, unmappedFields, err := createFieldMaps(ctx, s, srcStruct, dstStruct, &pair)
		if err != nil {
			return nil, fmt.Errorf("creating field maps for %s -> %s: %w", srcStruct.Name, dstStruct.Name, err)
		}

		// Discover new pairs from fields
		for _, fm := range fieldMaps {
			srcFieldType := getUnderlyingStructType(fm.SrcFieldT)
			dstFieldType := getUnderlyingStructType(fm.DstFieldT)

			if srcFieldType != nil && dstFieldType != nil {
				if srcFieldType.Definition == nil || dstFieldType.Definition == nil {
					slog.WarnContext(ctx, "could not resolve definition for field conversion", "src", srcFieldType.Name, "dst", dstFieldType.Name)
					continue
				}

				key := fmt.Sprintf("%s.%s -> %s.%s", srcFieldType.Definition.PkgPath, srcFieldType.Name, dstFieldType.Definition.PkgPath, dstFieldType.Name)
				if !processed[key] {
					slog.DebugContext(ctx, "Discovered required conversion", "key", key)
					newPair := model.ConversionPair{
						SrcTypeName: srcFieldType.Name,
						DstTypeName: dstFieldType.Name,
						SrcTypeInfo: srcFieldType.Definition,
						DstTypeInfo: dstFieldType.Definition,
					}
					worklist = append(worklist, newPair)
					processed[key] = true
				}
			}
		}

		allPairs = append(allPairs, TemplatePair{
			SrcType:        srcStruct,
			DstType:        dstStruct,
			Fields:         fieldMaps,
			Pair:           pair,
			UnmappedFields: unmappedFields,
		})
	}

	for _, rule := range info.GlobalRules {
		if rule.SrcTypeInfo != nil {
			im.Qualify(rule.SrcTypeInfo.PkgPath, rule.SrcTypeInfo.Name)
		}
		if rule.DstTypeInfo != nil {
			im.Qualify(rule.DstTypeInfo.PkgPath, rule.DstTypeInfo.Name)
		}
	}

	templateData := TemplateData{
		PackageName: info.PackageName,
		Imports:     im.Imports(),
		Pairs:       allPairs,
		Im:          im,
		Info:        info,
		Header:      header,
	}

	funcMap := template.FuncMap{
		"getAssignment": func(im *goscan.ImportManager, info *model.ParsedInfo, field FieldMap, srcVar, dstVar, ecVar, ctxVar string) string {
			return getAssignment(im, info, field, srcVar, dstVar, ecVar, ctxVar)
		},
		"getMapKeyAssignment": func(im *goscan.ImportManager, info *model.ParsedInfo, srcVar, dstVar string, srcT, dstT *scanner.FieldType, ecVar, ctxVar string) string {
			return getMapKeyAssignment(im, info, srcVar, dstVar, srcT, dstT, ecVar, ctxVar)
		},
		"getValidator": func(im *goscan.ImportManager, info *model.ParsedInfo, field FieldMap, dstVar, ecVar, ctxVar string) string {
			return getValidator(im, info, field, dstVar, ecVar, ctxVar)
		},
		"getQualifiedTypeName": func(im *goscan.ImportManager, structInfo *model.StructInfo) string {
			if structInfo == nil || structInfo.Type == nil {
				return "invalid"
			}
			// When generating code for a specific package, types within that package don't need qualification.
			if structInfo.Type.PkgPath == info.PackagePath {
				return structInfo.Name
			}
			return im.Qualify(structInfo.Type.PkgPath, structInfo.Name)
		},
	}

	tmpl, err := template.New("converter").Funcs(funcMap).Parse(codeTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	return buf.Bytes(), nil
}

func createFieldMaps(ctx context.Context, s *goscan.Scanner, src, dst *model.StructInfo, pair *model.ConversionPair) ([]FieldMap, []string, error) {
	var maps []FieldMap
	dstFieldsByName := make(map[string]model.FieldInfo)
	dstFieldsByNormalizedJSONTag := make(map[string]model.FieldInfo)
	dstFieldsByNormalizedName := make(map[string]model.FieldInfo)
	unmappedDstFields := make(map[string]bool)

	slog.DebugContext(ctx, "Destination struct", "name", dst.Name)
	for _, f := range dst.Fields {
		dstFieldsByName[f.Name] = f
		if f.JSONTag != "" && f.JSONTag != "-" {
			normalized := normalizeFieldName(f.JSONTag)
			dstFieldsByNormalizedJSONTag[normalized] = f
			slog.DebugContext(ctx, "dst field", "name", f.Name, "json", f.JSONTag, "normalized_json", normalized)
		}
		normalized := normalizeFieldName(f.Name)
		dstFieldsByNormalizedName[normalized] = f
		slog.DebugContext(ctx, "dst field", "name", f.Name, "normalized_name", normalized)
		unmappedDstFields[f.Name] = true
	}

	// Remove computed fields from the unmapped list
	for _, computed := range pair.Computed {
		delete(unmappedDstFields, computed.DstName)
	}

	slog.DebugContext(ctx, "Source struct", "name", src.Name)
	for _, srcField := range src.Fields {
		_ = resolveFieldType(ctx, s, srcField.FieldType)
		if srcField.Tag.DstFieldName == "-" {
			slog.DebugContext(ctx, "src field skipped by `convert:\"-\"`", "name", srcField.Name)
			continue
		}

		var dstField model.FieldInfo
		var ok bool
		var reason string

		// Priority 1: `convert` tag
		if srcField.Tag.DstFieldName != "" {
			dstField, ok = dstFieldsByName[srcField.Tag.DstFieldName]
			reason = fmt.Sprintf("`convert` tag (%s)", srcField.Tag.DstFieldName)
		}

		// Priority 2: Normalized `json` tag
		if !ok && srcField.JSONTag != "" && srcField.JSONTag != "-" {
			normalizedJSONTag := normalizeFieldName(srcField.JSONTag)
			dstField, ok = dstFieldsByNormalizedJSONTag[normalizedJSONTag]
			reason = fmt.Sprintf("normalized `json` tag (%s -> %s)", srcField.JSONTag, normalizedJSONTag)
		}

		// Priority 3: Normalized field name
		if !ok {
			normalizedSrcName := normalizeFieldName(srcField.Name)
			dstField, ok = dstFieldsByNormalizedName[normalizedSrcName]
			reason = fmt.Sprintf("normalized name (%s -> %s)", srcField.Name, normalizedSrcName)
		}

		if !ok {
			slog.DebugContext(ctx, "src field no match found", "name", srcField.Name)
			continue
		}

		slog.DebugContext(ctx, "src field matched", "src", srcField.Name, "dst", dstField.Name, "reason", reason)
		delete(unmappedDstFields, dstField.Name)
		_ = resolveFieldType(ctx, s, dstField.FieldType)
		maps = append(maps, FieldMap{
			SrcName:   srcField.Name,
			DstName:   dstField.Name,
			Tag:       srcField.Tag,
			SrcFieldT: srcField.FieldType,
			DstFieldT: dstField.FieldType,
		})
	}

	// Collect unmapped fields
	var unmapped []string
	for fieldName := range unmappedDstFields {
		unmapped = append(unmapped, fieldName)
	}
	// sort for deterministic output
	slices.Sort(unmapped)

	return maps, unmapped, nil
}

func normalizeFieldName(name string) string {
	return strings.ToLower(strings.ReplaceAll(name, "_", ""))
}

func resolveFieldType(ctx context.Context, s *goscan.Scanner, ft *scanner.FieldType) error {
	if ft == nil {
		return nil
	}
	if _, err := s.ResolveType(ctx, ft); err != nil {
		// Non-fatal, just log it. The type might not be resolvable in this context.
		slog.DebugContext(ctx, "could not resolve field type", "type", ft.Name, "error", err.Error())
	}
	if ft.Elem != nil {
		if err := resolveFieldType(ctx, s, ft.Elem); err != nil {
			return fmt.Errorf("resolving element type: %w", err)
		}
	}
	if ft.MapKey != nil {
		if err := resolveFieldType(ctx, s, ft.MapKey); err != nil {
			return fmt.Errorf("resolving map key type: %w", err)
		}
	}
	return nil
}

// -----------------------------------------------------------------------------
// Validator Logic
// -----------------------------------------------------------------------------

func getValidator(im *goscan.ImportManager, info *model.ParsedInfo, field FieldMap, dstVar, ecVar, ctxVar string) string {
	dstFieldT := field.DstFieldT
	dstFieldTypeName := getFullTypeNameFromFieldType(dstFieldT)
	dst := fmt.Sprintf("%s.%s", dstVar, field.DstName)

	for _, rule := range info.GlobalRules {
		if rule.ValidatorFunc == "" {
			continue
		}

		ruleDstName := getFullTypeNameFromTypeInfo(rule.DstTypeInfo)
		if ruleDstName == dstFieldTypeName {
			funcName := qualifyFunc(im, info, rule.ValidatorFunc)
			return fmt.Sprintf("%s(%s, %s)", funcName, ecVar, dst)
		}
	}
	return ""
}

func qualifyFunc(im *goscan.ImportManager, info *model.ParsedInfo, funcName string) string {
	parts := strings.Split(funcName, ".")
	if len(parts) != 2 {
		return funcName // Not a qualified function name, assume it's in the current package
	}
	alias, name := parts[0], parts[1]
	path, ok := info.Imports[alias]
	if !ok {
		slog.Warn("could not find import path for alias in function", "alias", alias, "funcName", funcName)
		return funcName
	}
	finalAlias := im.Add(path, alias)
	return finalAlias + "." + name
}

func registerImports(im *goscan.ImportManager, t *scanner.FieldType) {
	if t == nil {
		return
	}
	im.Qualify(t.FullImportPath, t.Name)
	if t.Elem != nil {
		registerImports(im, t.Elem)
	}
	if t.MapKey != nil {
		registerImports(im, t.MapKey)
	}
	for _, arg := range t.TypeArgs {
		registerImports(im, arg)
	}
}

// -----------------------------------------------------------------------------
// Assignment Logic
// -----------------------------------------------------------------------------

type ruleMatchResult struct {
	Rule           *model.TypeRule
	IsPointerMatch bool
}

func findMatchingRule(info *model.ParsedInfo, srcT, dstT *scanner.FieldType) *ruleMatchResult {
	if srcT == nil || dstT == nil {
		return nil
	}

	srcFieldTypeName := getFullTypeNameFromFieldType(srcT)
	dstFieldTypeName := getFullTypeNameFromFieldType(dstT)

	for i := range info.GlobalRules {
		rule := &info.GlobalRules[i]
		if rule.UsingFunc == "" {
			continue
		}

		// Use the raw type names from the rule, which preserve pointers.
		if rule.SrcTypeName == srcFieldTypeName && rule.DstTypeName == dstFieldTypeName {
			// Determine if it's a pointer match based on the source field type.
			// This is simpler than trying to infer from the rule's TypeInfo.
			return &ruleMatchResult{Rule: rule, IsPointerMatch: srcT.IsPointer}
		}
	}

	return nil
}

func getMapKeyAssignment(im *goscan.ImportManager, info *model.ParsedInfo, srcVar, dstVar string, srcT, dstT *scanner.FieldType, ecVar, ctxVar string) string {
	// Global conversion rule
	if match := findMatchingRule(info, srcT, dstT); match != nil {
		funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
		if dstVar != "" {
			return fmt.Sprintf("%s = %s(%s, %s, %s)", dstVar, funcName, ctxVar, ecVar, srcVar)
		}
		return fmt.Sprintf("%s(%s, %s, %s)", funcName, ctxVar, ecVar, srcVar)
	}
	return generateConversion(im, info, srcVar, dstVar, srcT, dstT, 0, ecVar, ctxVar)
}

func getAssignment(im *goscan.ImportManager, info *model.ParsedInfo, field FieldMap, srcVar, dstVar, ecVar, ctxVar string) string {
	src := fmt.Sprintf("%s.%s", srcVar, field.SrcName)
	dst := fmt.Sprintf("%s.%s", dstVar, field.DstName)

	// Priority 1: Field-level using tag
	if field.Tag.UsingFunc != "" {
		funcName := qualifyFunc(im, info, field.Tag.UsingFunc)
		return fmt.Sprintf("%s = %s(%s, %s, %s)", dst, funcName, ctxVar, ecVar, src)
	}

	// Priority 2: Global conversion rule
	if match := findMatchingRule(info, field.SrcFieldT, field.DstFieldT); match != nil {
		funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
		// The user-provided rule function is expected to have the correct signature
		// (e.g., handle pointers correctly). We just call it.
		return fmt.Sprintf("%s = %s(%s, %s, %s)", dst, funcName, ctxVar, ecVar, src)
	}

	if field.Tag.Required && field.SrcFieldT.IsPointer {
		return fmt.Sprintf("if %s == nil {\n\t%s.Add(fmt.Errorf(\"%s is required\"))\n} else {\n\t%s\n}", src, ecVar, field.SrcName, generateConversion(im, info, src, dst, field.SrcFieldT, field.DstFieldT, 0, ecVar, ctxVar))
	}

	// Priority 3: Default conversion logic
	return generateConversion(im, info, src, dst, field.SrcFieldT, field.DstFieldT, 0, ecVar, ctxVar)
}

func generateConversion(im *goscan.ImportManager, info *model.ParsedInfo, src, dst string, srcT, dstT *scanner.FieldType, depth int, ecVar, ctxVar string) string {
	// Global conversion rule
	if match := findMatchingRule(info, srcT, dstT); match != nil {
		funcName := qualifyFunc(im, info, match.Rule.UsingFunc)
		result := fmt.Sprintf("%s(%s, %s, %s)", funcName, ctxVar, ecVar, src)
		if dst != "" {
			return fmt.Sprintf("%s = %s", dst, result)
		}
		return result
	}

	if srcT == nil || dstT == nil {
		return fmt.Sprintf("// srcT or dstT is nil for %s -> %s", src, dst)
	}

	// Pointer to Pointer
	if srcT.IsPointer && dstT.IsPointer {
		if srcT.Elem == nil || dstT.Elem == nil {
			// Fallback for unresolved types or built-in pointers like *int
			if dst != "" {
				return fmt.Sprintf("%s = %s", dst, src)
			}
			return src
		}

		// If the elements are structs that have a dedicated converter, use it directly.
		if isStruct(srcT.Elem) && isStruct(dstT.Elem) {
			return fmt.Sprintf("convert%sTo%s(%s, %s, %s)", srcT.Elem.Name, dstT.Elem.Name, ctxVar, ecVar, src)
		}

		var b strings.Builder
		if dst != "" {
			// If dst is specified, we generate a block of statements.
			b.WriteString(fmt.Sprintf("if %s != nil {\n", src))
			b.WriteString(fmt.Sprintf("\ttmp := %s\n", generateConversion(im, info, "(*"+src+")", "", srcT.Elem, dstT.Elem, depth+1, ecVar, ctxVar)))
			b.WriteString(fmt.Sprintf("\t%s = &tmp\n", dst))
			b.WriteString("} else {\n")
			b.WriteString(fmt.Sprintf("\t%s = nil\n", dst))
			b.WriteString("}")
		} else {
			// If dst is empty, we must generate an expression, which we do with an anonymous func.
			b.WriteString(fmt.Sprintf("func() %s {\n", getTypeName(im, dstT)))
			b.WriteString(fmt.Sprintf("\tif %s == nil { return nil }\n", src))
			b.WriteString(fmt.Sprintf("\ttmp := %s\n", generateConversion(im, info, "(*"+src+")", "", srcT.Elem, dstT.Elem, depth+1, ecVar, ctxVar)))
			b.WriteString("\treturn &tmp\n")
			b.WriteString("}()")
		}
		return b.String()
	}
	// Pointer to Value
	if srcT.IsPointer && !dstT.IsPointer {
		if srcT.Elem == nil {
			return fmt.Sprintf("// Cannot convert pointer to value, element type is nil")
		}
		return fmt.Sprintf("if %s != nil {\n\t%s\n}", src, generateConversion(im, info, "(*"+src+")", dst, srcT.Elem, dstT, depth+1, ecVar, ctxVar))
	}
	// Value to Pointer
	if !srcT.IsPointer && dstT.IsPointer {
		if dstT.Elem == nil {
			return fmt.Sprintf("// Cannot convert value to pointer, element type is nil")
		}
		var b strings.Builder
		b.WriteString("{\n")
		b.WriteString(fmt.Sprintf("\ttmp := %s\n", generateConversion(im, info, src, "", srcT, dstT.Elem, depth+1, ecVar, ctxVar)))
		if dst != "" {
			b.WriteString(fmt.Sprintf("\t%s = &tmp\n", dst))
		} else {
			b.WriteString(fmt.Sprintf("\treturn &tmp\n"))
		}
		b.WriteString("}")
		return b.String()
	}

	// Slices
	if srcT.IsSlice && dstT.IsSlice {
		return generateSliceConversion(im, info, src, dst, srcT, dstT, depth, ecVar, ctxVar)
	}

	// Maps
	if srcT.IsMap && dstT.IsMap {
		return generateMapConversion(im, info, src, dst, srcT, dstT, depth, ecVar, ctxVar)
	}

	// Structs
	if isStruct(srcT) && isStruct(dstT) && srcT.Name != "" && dstT.Name != "" {
		srcPtr := src
		if !srcT.IsPointer {
			srcPtr = "&" + src
		}
		conversion := fmt.Sprintf("*convert%sTo%s(%s, %s, %s)", srcT.Name, dstT.Name, ctxVar, ecVar, srcPtr)
		if dst != "" {
			return fmt.Sprintf("%s = %s", dst, conversion)
		}
		return conversion
	}

	// Basic assignment
	if dst != "" {
		return fmt.Sprintf("%s = %s", dst, src)
	}
	return src
}

func generateSliceConversion(im *goscan.ImportManager, info *model.ParsedInfo, src, dst string, srcT, dstT *scanner.FieldType, depth int, ecVar, ctxVar string) string {
	if srcT.Elem == nil || dstT.Elem == nil {
		return ""
	}

	var b strings.Builder
	if dst != "" {
		b.WriteString("{\n")
		b.WriteString(fmt.Sprintf("\tconvertedSlice := make([]%s, len(%s))\n", getTypeName(im, dstT.Elem), src))
		b.WriteString(fmt.Sprintf("\tfor i, item := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedSlice[i] = %s\n", generateConversion(im, info, "item", "", srcT.Elem, dstT.Elem, depth+2, ecVar, ctxVar)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s = convertedSlice\n", dst))
		b.WriteString("}")
	} else {
		b.WriteString(fmt.Sprintf("func() []%s {\n", getTypeName(im, dstT.Elem)))
		b.WriteString(fmt.Sprintf("\tconvertedSlice := make([]%s, len(%s))\n", getTypeName(im, dstT.Elem), src))
		b.WriteString(fmt.Sprintf("\tfor i, item := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%d]\", i))\n")
		b.WriteString(fmt.Sprintf("\t\tconvertedSlice[i] = %s\n", generateConversion(im, info, "item", "", srcT.Elem, dstT.Elem, depth+2, ecVar, ctxVar)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn convertedSlice\n")
		b.WriteString("}()")
	}
	return b.String()
}

func generateMapConversion(im *goscan.ImportManager, info *model.ParsedInfo, src, dst string, srcT, dstT *scanner.FieldType, depth int, ecVar, ctxVar string) string {
	if srcT.MapKey == nil || srcT.Elem == nil || dstT.MapKey == nil || dstT.Elem == nil {
		return ""
	}

	var b strings.Builder
	if dst != "" {
		b.WriteString("{\n")
		b.WriteString(fmt.Sprintf("\tconvertedMap := make(map[%s]%s, len(%s))\n", getTypeName(im, dstT.MapKey), getTypeName(im, dstT.Elem), src))
		b.WriteString(fmt.Sprintf("\tfor key, value := range %s {\n", src))
		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%v]\", key))\n")
		keyExpr := "key"
		if getFullTypeNameFromTypeInfo(srcT.MapKey.Definition) != getFullTypeNameFromTypeInfo(dstT.MapKey.Definition) {
			keyExpr = getMapKeyAssignment(im, info, "key", "", srcT.MapKey, dstT.MapKey, ecVar, ctxVar)
		}
		b.WriteString(fmt.Sprintf("\t\tconvertedMap[%s] = %s\n",
			keyExpr,
			generateConversion(im, info, "value", "", srcT.Elem, dstT.Elem, depth+2, ecVar, ctxVar)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s = convertedMap\n", dst))
		b.WriteString("}")
	} else {
		b.WriteString(fmt.Sprintf("func() map[%s]%s {\n", getTypeName(im, dstT.MapKey), getTypeName(im, dstT.Elem)))
		b.WriteString(fmt.Sprintf("\tconvertedMap := make(map[%s]%s, len(%s))\n", getTypeName(im, dstT.MapKey), getTypeName(im, dstT.Elem), src))
		b.WriteString(fmt.Sprintf("\tfor key, value := range %s {\n", src))

		b.WriteString("\t\t" + ecVar + ".Enter(fmt.Sprintf(\"[%v]\", key))\n")
		keyExpr := "key"
		if getFullTypeNameFromTypeInfo(srcT.MapKey.Definition) != getFullTypeNameFromTypeInfo(dstT.MapKey.Definition) {
			keyExpr = getMapKeyAssignment(im, info, "key", "", srcT.MapKey, dstT.MapKey, ecVar, ctxVar)
		}
		b.WriteString(fmt.Sprintf("\t\tconvertedMap[%s] = %s\n",
			keyExpr,
			generateConversion(im, info, "value", "", srcT.Elem, dstT.Elem, depth+2, ecVar, ctxVar)))
		b.WriteString("\t\t" + ecVar + ".Leave()\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn convertedMap\n")
		b.WriteString("}()")
	}
	return b.String()
}

func getTypeName(im *goscan.ImportManager, t *scanner.FieldType) string {
	if t == nil {
		return "interface{}" // Should not happen in valid code
	}

	var sb strings.Builder

	if t.IsPointer {
		sb.WriteString("*")
		if t.Elem != nil {
			sb.WriteString(getTypeName(im, t.Elem))
		} else {
			sb.WriteString(im.Qualify(t.FullImportPath, t.Name))
		}
		return sb.String()
	}

	if t.IsSlice {
		sb.WriteString("[]")
		sb.WriteString(getTypeName(im, t.Elem))
		return sb.String()
	}

	if t.IsMap {
		keyType := getTypeName(im, t.MapKey)
		valType := getTypeName(im, t.Elem)
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return im.Qualify(t.FullImportPath, t.Name)
}

func isStruct(t *scanner.FieldType) bool {
	if t == nil {
		return false
	}
	if t.IsPointer {
		if t.Elem == nil {
			return false
		}
		return isStruct(t.Elem)
	}
	return t.Definition != nil && t.Definition.Kind == scanner.StructKind && !t.IsResolvedByConfig
}

func getUnderlyingStructType(t *scanner.FieldType) *scanner.FieldType {
	if t == nil {
		return nil
	}
	if t.IsPointer || t.IsSlice {
		return getUnderlyingStructType(t.Elem)
	}
	if t.IsMap {
		return getUnderlyingStructType(t.Elem)
	}
	if t.Definition != nil && t.Definition.Kind == scanner.StructKind {
		return t
	}
	return nil
}

func getFullTypeNameFromFieldType(ft *scanner.FieldType) string {
	if ft == nil {
		return ""
	}

	prefix := ""
	baseType := ft
	if ft.IsPointer {
		prefix = "*"
		if ft.Elem != nil {
			baseType = ft.Elem
		}
	}

	def := baseType.Definition
	if def == nil && ft.Definition != nil {
		def = ft.Definition
	}

	if def != nil && def.PkgPath != "" {
		return prefix + def.PkgPath + "." + def.Name
	}

	if baseType.FullImportPath != "" {
		return prefix + baseType.FullImportPath + "." + baseType.Name
	}
	if baseType.Name != "" {
		return prefix + baseType.Name
	}
	return ""
}

func getFullTypeNameFromTypeInfo(t *scanner.TypeInfo) string {
	if t == nil {
		return ""
	}
	if t.PkgPath != "" {
		return fmt.Sprintf("%s.%s", t.PkgPath, t.Name)
	}
	if t.Name != "" {
		return t.Name
	}
	if t.Underlying != nil && t.Underlying.Definition != nil {
		return getFullTypeNameFromTypeInfo(t.Underlying.Definition)
	}
	if t.Underlying != nil {
		return t.Underlying.Name
	}
	return ""
}
