// Command stringer is a minigo-native String() generator — the kind of
// tool //minigo:generate exists for (issue #390): no go/types, no
// go/packages, just the inspect API over the scanned package's index.
//
// It runs two ways from one source: as an ordinary command
// (go run ./tools/stringer -type=X, main wraps Main in os.Args) and
// interpreted under minigo-generate, which calls Main(args) directly
// with the directive's arguments and delivers the file context through
// GOFILEPATH/GOPACKAGE env exactly like go generate.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/podhmo/minigo/inspect"
)

func main() {
	os.Exit(Main(os.Args[1:]))
}

// Main is the minigo-generate entry: args are the directive's arguments
// (argv[1:] of the equivalent command), not the process's os.Args.
func Main(args []string) int {
	fs := flag.NewFlagSet("stringer", flag.ContinueOnError)
	typ := fs.String("type", "", "generate String() for this named type")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *typ == "" {
		fmt.Fprintln(os.Stderr, "stringer: -type is required")
		return 2
	}
	gofile := os.Getenv("GOFILEPATH")
	if gofile == "" {
		fmt.Fprintln(os.Stderr, "stringer: GOFILEPATH is not set (run via minigo-generate)")
		return 2
	}
	dir := filepath.Dir(gofile)
	pkg := inspect.DirOf(dir)
	var target *inspect.Decl
	for _, f := range inspect.Files(pkg) {
		for _, d := range inspect.Decls(f) {
			if d.Name == *typ && inspect.Kind(d) == "type" {
				target = d
			}
		}
	}
	if target == nil {
		fmt.Fprintf(os.Stderr, "stringer: no type %s in package %s\n", *typ, inspect.Path(pkg))
		return 1
	}
	members := inspect.EnumMembers(target)
	if len(members) == 0 {
		fmt.Fprintf(os.Stderr, "stringer: type %s has no enum consts\n", *typ)
		return 1
	}
	src, err := emit(inspect.Name(pkg), *typ, target, members)
	if err != nil {
		fmt.Fprintln(os.Stderr, "stringer:", err)
		return 1
	}
	// go/format is bound natively by the runner — same call as a real
	// tool, and generated code is formatted like real stringer's.
	if formatted, ferr := format.Source(src); ferr == nil {
		src = formatted
	}
	out := filepath.Join(dir, strings.ToLower(*typ)+"_string.go")
	if err := os.WriteFile(out, src, 0644); err != nil {
		fmt.Fprintln(os.Stderr, "stringer:", err)
		return 1
	}
	fmt.Println("stringer: wrote", out)
	return 0
}

// emit renders <type>_string.go: a String() method as a name switch
// plus a numeric fallback, the same shape real stringer writes. The
// bytes still go through format.Source before being written, so the
// template only has to be approximately right.
func emit(pkg, typ string, target *inspect.Decl, members []*inspect.Decl) ([]byte, error) {
	def := inspect.Def(target)
	var fallback, impt string
	switch def.Text {
	case "string":
		fallback = `"` + typ + `(" + string(x) + ")"`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		impt = "\nimport \"strconv\"\n"
		fallback = `"` + typ + `(" + strconv.FormatInt(int64(x), 10) + ")"`
	default:
		return nil, fmt.Errorf("type %s: unsupported base type %s", typ, def.Text)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by minigo stringer -type=%s; DO NOT EDIT.\n\n", typ)
	fmt.Fprintf(&b, "package %s\n%s\n", pkg, impt)
	fmt.Fprintf(&b, "func (x %s) String() string {\n\tswitch x {\n", typ)
	for _, m := range members {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", m.Name, m.Name)
	}
	fmt.Fprintf(&b, "\t}\n\treturn %s\n}\n", fallback)
	return []byte(b.String()), nil
}
